<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Mobile2
 * @version    2.0.2
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><?php
/**
 * Product list template
 *
 * @see Mage_Catalog_Block_Product_List
 */
?>
<?php
$_productCollection=$this->getLoadedProductCollection();
$_helper = $this->helper('catalog/output');
?>
<div id="product_list" class="products">
    <?php if(!$_productCollection->count()): ?>
        <div class="no-products-msg">
            <?php echo $this->__('There are no products matching the selection.') ?>
        </div>
    <?php else: ?>
        <?php foreach ($_productCollection as $_product): ?>
            <div class="product-card" onclick="setLocation('<?php echo $_product->getProductUrl() ?>')">
                <p class="product-card__image-wrapper">
                    <img class="product-card__image"   width="120" height="120"  alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(120); ?>" />
                </p>
                <div class="product-card__info">
                    <h3 class="product-card__title">
                        <a href="javascript:setLocation('<?php echo $_product->getProductUrl() ?>');void(0);">
                            <span class="product_title">
                                <?php echo $this->stripTags($_product->getName(), null, true) ?>
                            </span>
                        </a>
                    </h3>
                    <div style="clear:both"></div>
                    <?php echo $this->getReviewsSummaryHtml($_product, false, false)?>
                    <?php if (AW_Mobile2_Helper_Config::isCanDisplayStockStatusAtCatalog()):?>
                        <?php if($_product->isSaleable()): ?>
                            <p class="product-card__availability"><?php echo $this->__('In stock') ?></p>
                        <?php else: ?>
                            <p class="product-card__availability"><?php echo $this->__('Out of stock') ?></p>
                        <?php endif; ?>
                    <?php endif;?>
                    <div class="product-card__prices">
                        <p class="product-card__price">
                            <?php echo $this->getPriceHtml($_product, true);?>
                        </p>
                    </div>
                </div><!-- .product-card__info -->
            </div><!-- .product-card -->
        <?php endforeach; ?>
    <?php endif ?>
</div>
<?php echo $this->getToolbarHtml() ?>
<script type="text/javascript">
    //<![CDATA[
    if (typeof pager != 'undefined') {
        pager.containerId = 'product_list';
    }
    //]]>
</script>