<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Mobile2
 * @version    2.0.2
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><?php
/** @var $_coreHelper Mage_Core_Helper_Data */
$_coreHelper = $this->helper('core');
/** @var $_catalogHelper Mage_Catalog_Helper_Data */
$_catalogHelper = $this->helper('catalog');

/** @var $_product Mage_Catalog_Model_Product */
$_product = $this->getProduct();
$_id = $_product->getId();
$_msrpPrice = '';
$priceElementIdPrefix = $this->getPriceElementIdPrefix() ? $this->getPriceElementIdPrefix() : 'product-price-';
?>
<div class="price-box map-info">
    <?php $_price = $this->helper('tax')->getPrice($_product, $_product->getMsrp()) ?>
    <?php if($_product->getMsrp()): ?>
        <?php $_msrpPrice = $_coreHelper->currency($_product->getMsrp(),true,true) ?>
        <span class="old-price" ><?php echo $_msrpPrice ?></span>
    <?php endif; ?>
</div>