<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Mobile2
 * @version    2.0.2
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><?php /** @var $this Mage_Shipping_Block_Tracking_Popup */ ?>
<div class="shipping-tracking">
    <?php $_results = $this->getTrackingInfo(); ?>
    <?php if(sizeof($_results)>0): ?>
        <?php foreach($_results as $shipid => $_result): ?>
            <div class="order__section">
                <?php if($shipid): ?>
                    <h2 class="order__section-title"><?php echo $this->__('Shipment #').$shipid; ?></h2>
                <?php endif; ?>
                <?php if(sizeof($_result)>0): ?>
                    <?php $rowCount = sizeof($_result); $counter = 1; ?>
                    <?php $_id = 0; foreach($_result as $track): ?>
                        <?php if(is_object($track)): ?>
                            <p>
                                <?php echo $this->__('Tracking Number:'); ?><?php echo $this->escapeHtml($track->getTracking()); ?>
                            </p>
                            <?php if ($track->getCarrierTitle()): ?>
                            <p>
                                <?php echo $this->__('Carrier:'); ?><?php echo $this->escapeHtml($track->getCarrierTitle()); ?>
                            </p>
                            <?php endif; ?>
                            <?php if($track->getErrorMessage()): ?>
                                <p>
                                    <?php echo $this->__('Error:'); ?><?php echo $this->__('Tracking information is currently not available. Please '); if ($this->getContactUsEnabled()) : ?><a href="<?php echo $this->getContactUs() ?>" title="<?php echo $this->__('contact us') ?>" onclick="this.target='_blank'"><?php echo $this->__('contact us') ?></a><?php echo $this->__(' for more information or '); endif; echo $this->__('email us at '); ?><a href="mailto:<?php echo $this->getStoreSupportEmail() ?>"><?php echo $this->getStoreSupportEmail() ?></a>
                                </p>
                            <?php elseif($track->getTrackSummary()): ?>
                                <p>
                                    <?php echo $this->__('Info:'); ?><?php echo $track->getTrackSummary(); ?>
                                </p>
                            <?php elseif($track->getUrl()): ?>
                                <p>
                                    <?php echo $this->__('Track:'); ?><a href="<?php echo $this->escapeHtml($track->getUrl()); ?>" onclick="this.target='_blank'"><?php echo $this->escapeHtml($track->getUrl()); ?></a>
                                </p>
                            <?php else: ?>
                                <?php if ($track->getStatus()): ?>
                                    <p>
                                        <?php echo $this->__('Status:'); ?><?php echo $track->getStatus(); ?>
                                    </p>
                                <?php endif; ?>

                                <?php if ($track->getDeliverydate()): ?>
                                    <p>
                                        <?php echo $this->__('Delivered on:'); ?><?php echo $this->formatDeliveryDateTime($track->getDeliverydate(),$track->getDeliverytime()); ?>
                                    </p>
                                <?php endif; ?>

                                <?php if ($track->getSignedby()): ?>
                                    <p>
                                        <?php echo $this->__('Signed by:'); ?><?php echo $track->getSignedby(); ?>
                                    </p>
                                <?php endif; ?>

                                <?php if ($track->getDeliveryLocation()): ?>
                                    <p>
                                        <?php echo $this->__('Delivered to:'); ?><?php echo $track->getDeliveryLocation(); ?>
                                    </p>
                                <?php endif; ?>

                                <?php if ($track->getShippedDate()): ?>
                                    <p>
                                        <?php echo $this->__('Shipped or billed on:'); ?><?php echo $track->getShippedDate(); ?>
                                    </p>
                                <?php endif; ?>

                                <?php if ($track->getService()): ?>
                                    <p>
                                        <?php echo $this->__('Service Type:'); ?><?php echo $track->getService(); ?>
                                    </p>
                                <?php endif; ?>

                                <?php if ($track->getWeight()): ?>
                                    <p>
                                        <?php echo $this->__('Weight:'); ?><?php echo $track->getWeight(); ?>
                                    </p>
                                <?php endif; ?>
                            <?php endif; ?>
                        <?php elseif(isset($track['title']) && isset($track['number']) && $track['number']): ?>
                            <!--if the tracking is custom value-->
                            <p>
                                <?php echo ($track['title'] ? $this->escapeHtml($track['title']) : $this->__('N/A')); ?>:<?php echo (isset($track['number']) ? $this->escapeHtml($track['number']) : ''); ?>
                            </p>
                        <?php endif; ?>
                        <?php if (is_object($track) && sizeof($track->getProgressdetail())>0): ?>
                            <table class="data-table" id="track-history-table-<?php echo $track->getTracking(); ?>">
                                <thead>
                                <tr>
                                    <th><?php echo $this->__('Location') ?></th>
                                    <th><?php echo $this->__('Date') ?></th>
                                    <th><?php echo $this->__('Local Time') ?></th>
                                    <th><?php echo $this->__('Description') ?></th>
                                </tr>
                                </thead>
                                <tbody>
                                <?php foreach($track->getProgressdetail() as $_detail): ?>
                                    <?php $_detailDate = (isset($_detail['deliverydate']) ? $this->formatDeliveryDate($_detail['deliverydate']) : '') ?>
                                    <?php $_detailTime = (isset($_detail['deliverytime']) ? $this->formatDeliveryTime($_detail['deliverytime'], $_detail['deliverydate']) : '') ?>
                                    <tr class="data-table-row">
                                        <td><?php echo (isset($_detail['deliverylocation']) ? $_detail['deliverylocation'] : ''); ?></td>
                                        <td><span class="nobr"><?php echo $_detailDate ?></span></td>
                                        <td><span class="nobr"><?php echo $_detailTime ?></span></td>
                                        <td><?php echo (isset($_detail['activity']) ? $_detail['activity'] : '') ?></td>
                                    </tr>
                                <?php endforeach; ?>
                                </tbody>
                            </table>
                        <?php endif; ?>
                        <?php if($counter!=$rowCount): ?>
                        <?php endif; ?>
                        <?php $counter++; ?>
                        <!--end for each tracking information-->
                    <?php endforeach; ?>
                <?php else: ?>
                    <p><?php echo $this->__('There is no tracking available for this shipment.'); ?></p>
                <?php endif; ?>
            </div>
        <?php endforeach; ?>
    <?php else: ?>
        <p><?php echo $this->__('There is no tracking available.'); ?></p>
    <?php endif; ?>
</div>