<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Mobile2
 * @version    2.0.2
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><script type="text/javascript">
    //<![CDATA[
    window.customerAccount = new awMobile2.app.customerAccount('customer_account_link', 'customer_ajax_container');
    //]]>
</script>
<div id="customer_navigation_popup" class="nav_iphone customer-cart-ajax panel panel--from-bottom popup-form">
    <div id="customer_ajax_container">
        <?php echo $this->getChildHtml('customer_account_navigation')?>
    </div>
</div>
