<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Mobile2
 * @version    2.0.2
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><?php
/**
 * @see Mage_Authorizenet_Block_Directpost_Form
 */
?>
<?php
$_form = $this;
$_code = $_form->getMethodCode();
$_method = $_form->getMethod();
$_controller = $this->helper('authorizenet')->getControllerName();
$_orderUrl = $this->helper('authorizenet')->getPlaceOrderFrontUrl();
?>
<div class="buttons-set">
<!-- IFRAME for request to Authorize.net -->
<iframe id="directpost-iframe" allowtransparency="true" frameborder="0"  name="iframeDirectPost" style="display:none;width:100%;background-color:transparent" src="<?php echo $this->getJsUrl() ?>blank.html"></iframe>

<form id="co-directpost-form" action="#" method="post">
    <div class="fieldset">
        <div class="sp-methods">
            <h2 class="legend"><?php echo $this->__('Credit Card Information') ?></h2>
            <div id="payment_form_<?php echo $_code ?>" class="form-list">
                <p class="form__field form__field--required">
                    <label for="<?php echo $_code ?>_cc_type" class="form__label form__label--required"><?php echo $this->__('Credit Card Type') ?></label>
                    <select class="form__select required-entry validate-cc-type-select" id="<?php echo $_code ?>_cc_type" name="payment[cc_type]">
                        <option value=""><?php echo $this->__('--Please Select--')?></option>
                        <?php $_ccType = $this->getInfoData('cc_type') ?>
                        <?php foreach ($this->getCcAvailableTypes() as $_typeCode => $_typeName): ?>
                            <option value="<?php echo $_typeCode ?>"<?php if($_typeCode==$_ccType): ?> selected="selected"<?php endif ?>><?php echo $_typeName ?></option>
                        <?php endforeach ?>
                    </select>
                </p><!-- .form__field -->
                <p class="form__field form__field--required">
                    <label for="<?php echo $_code ?>_cc_number" class="form__label form__label--required"><?php echo $this->__('Card Number') ?><span class="step-comment"><?php echo $this->__('The long number on your card')?></span></label>
                    <input type="tel" id="<?php echo $_code ?>_cc_number" name="payment[cc_number]" title="<?php echo $this->__('Credit Card Number') ?>" class="form__textfield textfield required-entry validate-cc-number validate-cc-type" value="" />
                </p>
                <p class="form__field form__field--required" id="<?php echo $_code ?>_cc_type_exp_div">
                    <label for="<?php echo $_code ?>_expiration" class="form__label form__label--required"><?php echo $this->__('Expiration Date') ?><span class="step-comment"><?php echo $this->__('Expiration mouth and year')?></span></label>
                    <select id="<?php echo $_code ?>_expiration" name="payment[cc_exp_month]" class="form__select month validate-cc-exp required-entry">
                        <?php $_ccExpMonth = $this->getInfoData('cc_exp_month') ?>
                        <?php foreach ($this->getCcMonths() as $k=>$v): ?>
                            <option value="<?php echo $k?$k:'' ?>"<?php if($k==$_ccExpMonth): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                        <?php endforeach ?>
                    </select>
                    <?php $_ccExpYear = $this->getInfoData('cc_exp_year') ?>
                    <select id="<?php echo $_code ?>_expiration_yr" name="payment[cc_exp_year]" class="form__select year required-entry">
                        <?php foreach ($this->getCcYears() as $k=>$v): ?>
                            <option value="<?php echo $k?$k:'' ?>"<?php if($k==$_ccExpYear): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                        <?php endforeach ?>
                    </select>
                </p>
                <?php echo $_form->getChildHtml() ?>
                <?php if($_form->hasVerification()): ?>
                    <p id="<?php echo $_code ?>_cc_type_cvv_div" class="form__field form__field--required">
                        <label for="<?php echo $_code ?>_cc_cid" class="form__label form__label--required"><?php echo $this->__('CVV') ?><span class="step-comment"><?php echo $this->__('The 3/4 digit security code on your card')?></span></label>
                        <input type="tel" title="<?php echo $this->__('Card Verification Number') ?>" class="form__textfield textfield cvv required-entry validate-cc-cvn" id="<?php echo $_code ?>_cc_cid" name="payment[cc_cid]" value="" />
                    </p>
                <?php endif; ?>
            </div>
        </div>
    </div>
</form>
</div>
<div class="tool-tip" id="directpost-tool-tip" style="display:none;">
    <div class="btn-close"><a href="#" id="directpost-tool-tip-close" title="<?php echo $this->__('Close') ?>"><?php echo $this->__('Close') ?></a></div>
    <div class="tool-tip-content"><img src="<?php echo $this->getSkinUrl('images/cvv.gif') ?>" alt="<?php echo $this->__('Card Verification Number Visual Reference') ?>" title="<?php echo $this->__('Card Verification Number Visual Reference') ?>" /></div>
</div>
<script type="text/javascript">
//<![CDATA[
if ($('directpost-cvv-what-is-this')) {
    $('directpost-cvv-what-is-this').observe('click', toggleCvvToolTip);
}
new Validation('co-directpost-form');
function toggleCvvToolTip(event){
    if($('directpost-tool-tip')){
        $('directpost-tool-tip').setStyle({
            top: (Event.pointerY(event)-560)+'px'
        })
        $('directpost-tool-tip').toggle();
    }
    Event.stop(event);
}
if($('directpost-tool-tip-close')){
    Event.observe($('directpost-tool-tip-close'), 'click', toggleCvvToolTip);
}
directPostModel = new directPost(
    '<?php echo $_code ?>',
    'directpost-iframe',
    '<?php echo $_controller ?>',
    '<?php echo $_orderUrl ?>',
    '<?php echo $_method->getCgiUrl() ?>',
    '<?php echo $this->getUrl('checkout/onepage/saveOrder', array('_secure' => $this->getRequest()->isSecure())) ?>');
//]]>
</script>
