<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Mobile2
 * @version    2.0.2
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><?php
/** @var $this Enterprise_Rma_Block_Order_Button */
?>
<?php if($this->helper('enterprise_rma')->canCreateRma($this->getOrder())): ?>
<p class="order__reorder">
    <span class="separator">|</span>
    <a href="<?php echo $this->helper('enterprise_rma')->getReturnCreateUrl($this->getOrder()) ?>"><?php echo $this->__('Return') ?></a>
</p>
<?php endif;?>
