<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Mobile2
 * @version    2.0.2
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><form class="form" id="co-billing-form" action="">
    <?php if ($this->customerHasAddresses()): ?>
        <p class="form__field form__field--required">
            <label class="form__label">
                <?php echo $this->__('Select a billing address from your address book or enter a new address.') ?>
            </label>
            <?php echo $this->getAddressesHtmlSelect('billing') ?>
        </p><!-- .form__field -->
    <?php endif; ?>
    <div id="billing-new-address-form" <?php if ($this->customerHasAddresses()): ?> style="display:none;"<?php endif ?>>
        <?php echo $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getAddress())->setFieldIdFormat('billing:%s')->setFieldNameFormat('billing[%s]')->toHtml() ?>
        <p class="form__field">
            <label class="form__label" for="billing:company"><?php echo $this->__('Company') ?></label>
            <input type="text" class="form__textfield textfield" id="billing:company" name="billing[company]" value="<?php echo $this->htmlEscape($this->getAddress()->getCompany()) ?>" title="<?php echo $this->__('Company') ?>">
        </p><!-- .form__field -->
        <?php if(!$this->isCustomerLoggedIn()): ?>
            <p class="form__field form__field--required">
                <label for="billing:email" class="form__label form__label--required"><?php echo $this->__('Email Address') ?></label>
                <input type="email" class="form__textfield textfield validate-email required-entry" name="billing[email]" id="billing:email" value="<?php echo $this->htmlEscape($this->getAddress()->getEmail()) ?>" title="<?php echo $this->__('Email Address') ?>">
            </p><!-- .form__field -->
        <?php endif ?>
        <p class="form__field form__field--required">
            <label for="billing:street1" class="form__label form__label--required"><?php echo $this->__('Address') ?></label>
            <input type="text" class="form__textfield textfield required-entry" title="<?php echo $this->__('Street Address') ?>" name="billing[street][]" id="billing:street1" value="<?php echo $this->htmlEscape($this->getAddress()->getStreet(1)) ?>">
        </p><!-- .form__field -->
        <?php for ($_i=2, $_n=$this->helper('customer/address')->getStreetLines(); $_i<=$_n; $_i++): ?>
            <p class="form__field">
                <label class="form__label" for="billing:street<?php echo $_i?>"><?php echo $this->__('Street Address %s', $_i) ?></label>
                <input type="text" class="form__textfield textfield" title="<?php echo $this->__('Street Address %s', $_i) ?>" name="billing[street][]" id="billing:street<?php echo $_i?>" value="<?php echo $this->htmlEscape($this->getAddress()->getStreet($_i)) ?>">
            </p><!-- .form__field -->
        <?php endfor ?>
        <p class="form__field form__field--required">
            <label class="form__label form__label--required" for="billing:city"><?php echo $this->__('City') ?></label>
            <input type="text" class="form__textfield textfield required-entry" title="<?php echo $this->__('City') ?>" id="billing:city" name="billing[city]" value="<?php echo $this->htmlEscape($this->getAddress()->getCity()) ?>">
        </p><!-- .form__field -->
        <p class="form__field form__field--required">
            <label class="form__label form__label--required" for="billing:region_id"><?php echo $this->__('State/Province') ?></label>
            <select class="form__select validate-select" id="billing:region_id" name="billing[region_id]" title="<?php echo $this->__('State/Province') ?>" style="display:none;">
                <option value=""><?php echo $this->__('Please select region, state or province') ?></option>
            </select>
            <script type="text/javascript">
                //<![CDATA[
                $('billing:region_id').setAttribute('defaultValue',  "<?php echo $this->getAddress()->getRegionId() ?>");
                //]]>
            </script>
            <input type="text" id="billing:region" name="billing[region]" value="<?php echo $this->htmlEscape($this->getAddress()->getRegion()) ?>"  title="<?php echo $this->__('State/Province') ?>" class="form__textfield textfield" style="display:none;" />
        </p><!-- .form__field -->
        <p class="form__field form__field--required">
            <label for="billing:postcode" class="form__label form__label--required"><?php echo $this->__('Zip/Postal Code') ?></label>
            <input type="text" class="form__textfield textfield validate-zip-international required-entry" title="<?php echo $this->__('Zip/Postal Code') ?>" name="billing[postcode]" id="billing:postcode" value="<?php echo $this->htmlEscape($this->getAddress()->getPostcode()) ?>" />
        </p><!-- .form__field -->
        <p class="form__field form__field--required">
            <label class="form__label form__label--required" for="billing:country_id"><?php echo $this->__('Country') ?></label>
            <?php echo $this->getCountryHtmlSelect('billing') ?>
        </p><!-- .form__field -->
        <p class="form__field form__field--required">
            <label for="billing:telephone" class="form__label form__label--required"><?php echo $this->__('Telephone') ?></label>
            <input type="tel" class="form__textfield textfield required-entry" name="billing[telephone]" value="<?php echo $this->htmlEscape($this->getAddress()->getTelephone()) ?>" title="<?php echo $this->__('Telephone') ?>" id="billing:telephone" />
        </p><!-- .form__field -->
        <p class="form__field">
            <label class="form__label" for="billing:fax"><?php echo $this->__('Fax') ?></label>
            <input type="tel" id="billing:fax" class="form__textfield textfield" name="billing[fax]" value="<?php echo $this->htmlEscape($this->getAddress()->getFax()) ?>" title="<?php echo $this->__('Fax') ?>">
        </p><!-- .form__field -->

        <?php $addressAttributes = $this->getChild('customer_form_billing_address_user_defined_attributes');?>
        <?php if ($addressAttributes && $addressAttributes instanceof Enterprise_Customer_Block_Form): ?>
            <?php $addressAttributes->setEntity($this->getAddress())->setEntityType('customer_address');?>
            <?php $addressAttributes->setFieldIdFormat('billing:%1$s')->setFieldNameFormat('billing[%1$s]');?>
            <?php echo $addressAttributes->setExcludeFileAttributes(true)->setShowContainer(false)->toHtml()?>
        <?php endif;?>

        <?php if(!$this->isCustomerLoggedIn()): ?>
            <?php $_dob = $this->getLayout()->createBlock('customer/widget_dob')->setClassName('checkout_customer_dob')?>
            <?php $_gender = $this->getLayout()->createBlock('customer/widget_gender') ?>
            <?php if ($_dob->isEnabled() || $_gender->isEnabled()): ?>
                <?php if ($_dob->isEnabled()): ?>
                    <?php echo $_dob->setDate($this->getQuote()->getCustomerDob())->setFieldIdFormat('billing:%s')->setFieldNameFormat('billing[%s]')->toHtml() ?>
                <?php endif; ?>
                <?php if ($_gender->isEnabled()): ?>
                    <?php echo $_gender->setGender($this->getQuote()->getCustomerGender())->setFieldIdFormat('billing:%s')->setFieldNameFormat('billing[%s]')->toHtml() ?>
                <?php endif ?>
            <?php endif ?>

            <?php $customerAttributes = $this->getChild('customer_form_customer_user_defined_attributes');?>
            <?php if ($customerAttributes && $customerAttributes instanceof Enterprise_Customer_Block_Form): ?>
                <?php $customerAttributes->setEntityModelClass('customer/customer')->setFieldIdFormat('billing:%1$s');?>
                <?php $customerAttributes->setFieldNameFormat('billing[%1$s]')->setShowContainer(false);?>
                <?php echo $customerAttributes->setExcludeFileAttributes(true)->toHtml()?>
            <?php endif;?>

            <?php $_taxvat = $this->getLayout()->createBlock('customer/widget_taxvat') ?>
            <?php if ($_taxvat->isEnabled()): ?>
                <?php echo $_taxvat->setTaxvat($this->getQuote()->getCustomerTaxvat())->setFieldIdFormat('billing:%s')->setFieldNameFormat('billing[%s]')->toHtml() ?>
            <?php endif ?>
            <div id="register-customer-password">
                <p class="form__field form__field--required">
                    <label for="billing:customer_password" class="form__label form__label--required"><?php echo $this->__('Password') ?></label>
                    <input class="form__textfield textfield required-entry validate-password" type="password" name="billing[customer_password]" id="billing:customer_password" title="<?php echo $this->__('Password') ?>" />
                </p><!-- .form__field -->
                <p class="form__field form__field--required">
                    <label for="billing:confirm_password" class="form__label form__label--required"><?php echo $this->__('Confirm Password') ?></label>
                    <input class="form__textfield textfield required-entry validate-cpassword" type="password" name="billing[confirm_password]" title="<?php echo $this->__('Confirm Password') ?>" id="billing:confirm_password" />
                </p><!-- .form__field -->
            </div>
        <?php endif ?>
        <?php if ($this->isCustomerLoggedIn() && $this->customerHasAddresses()):?>
            <div class="form__field">
                <ul class="form__checkboxes">
                    <li class="form__checkboxes-item">
                        <input type="checkbox" name="billing[save_in_address_book]" value="1" title="<?php echo $this->__('Save in address book') ?>" id="billing:save_in_address_book" onchange="if(window.shipping) shipping.setSameAsBilling(false);"<?php if ($this->getAddress()->getSaveInAddressBook()):?> checked="checked"<?php endif;?> class="form__checkbox" />
                        <label class="form__checkbox-label" for="billing:save_in_address_book"><?php echo $this->__('Save in address book') ?></label>
                    </li>
                </ul>
            </div>
        <?php else:?>
            <div class="no-display">
                <input type="hidden" name="billing[save_in_address_book]" value="1" />
            </div>
        <?php endif; ?>
        <?php echo $this->getChildHtml('form.additional.info'); ?>
    </div>
    <?php if ($this->canShip()): ?>
        <div class="form__field form__field--required" style="display:none;">
            <ul class="form__radios">
                <li class="form__radios-item">
                    <input type="radio" class="form__radio" name="billing[use_for_shipping]" id="billing:use_for_shipping_yes" value="1"<?php if ($this->isUseBillingAddressForShipping()) {?> checked="checked"<?php }?> title="<?php echo  $this->__('Ship to this address') ?>" onclick="$('shipping:same_as_billing').checked = true;">
                    <label class="form__radio-label">
                        <?php echo  $this->__('Ship to this address') ?>
                    </label>
                </li>
                <li class="form__radios-item">
                    <input type="radio" class="form__radio" name="billing[use_for_shipping]" id="billing:use_for_shipping_no" value="0"<?php if (!$this->isUseBillingAddressForShipping()) {?> checked="checked"<?php }?> title="<?php echo $this->__('Ship to different address') ?>" onclick="$('shipping:same_as_billing').checked = false;" >
                    <label class="form__radio-label">
                        <?php echo $this->__('Ship to different address') ?>
                    </label>
                </li>
            </ul>
        </div><!-- .form__field -->
    <?php endif; ?>
    <?php if (!$this->canShip()): ?>
        <input type="hidden" name="billing[use_for_shipping]" value="1" />
    <?php endif; ?>
    <div>
        <p class="form__submit-wrapper" id="billing-buttons-container">
            <?php if ($this->canShip()):?>
                <button type="button" onclick="$('billing:use_for_shipping_yes').checked = true;setStepDescription('billing', getBillingStepDescription());billing.save();setStepDescription('shipping', getBillingStepDescription());" class="form__submit button continue"><?php echo $this->__('Ship to this address') ?></button>
                <button type="button" onclick="$('billing:use_for_shipping_no').checked = true;setStepDescription('billing', getBillingStepDescription());billing.save()" class="form__submit button continue-another"><?php echo $this->__('Ship to another address') ?></button>
            <?php else:?>
                <button type="button" onclick="setStepDescription('billing', getBillingStepDescription());billing.save()" class="form__submit button continue"><?php echo $this->__('Continue') ?></button>
            <?php endif; ?>
        </p><!-- .form__submit-wrapper -->
    </div>
</form>
<script type="text/javascript">
    //<![CDATA[
    var billing = new Billing('co-billing-form', '<?php echo $this->getUrl('checkout/onepage/getAddress') ?>address/', '<?php echo $this->getUrl('checkout/onepage/saveBilling') ?>');
    var billingForm = new VarienForm('co-billing-form');
    $('billing-address-select') && billing.newAddress(!$('billing-address-select').value);
    var billingRegionUpdater = new RegionUpdater('billing:country_id', 'billing:region', 'billing:region_id', countryRegions, undefined, 'billing:postcode');
    var getBillingStepDescription = function()
    {
        return '<p>'+$('billing:firstname').value+' '+$('billing:lastname').value+'</p>'
            + '<p>'+$('billing:street1').value+','+'</p>'
            + '<p>'+$('billing:telephone').value+'</p>'
        ;
    };
    $('co-billing-form').select('.textfield').each(function(el){
        el.observe('keypress', function(e){
            if (e.keyCode !== 13) {
                return;
            }
            var nextFormField = el.up('.form__field').next('.form__field');
            if (nextFormField && nextFormField.down('.textfield')) {
                nextFormField.down('.textfield').focus();
            }
        });
    });
    //]]>
</script>