<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Mobile2
 * @version    2.0.2
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><?php echo $this->getChildHtml('login_before')?>
<h3 class="checkout-method__title login">
    <?php echo $this->__('Sign in') ?>
</h3>
<form class="checkout-method form" id="checkout-login-form" action="<?php echo $this->getPostAction() ?>" method="post">
    <?php echo $this->getBlockHtml('formkey'); ?>
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <p class="form__field">
        <label class="form__label"><?php echo $this->__('Email') ?></label>
        <input type="email" class="form__textfield textfield required-entry validate-email" id="login-email" name="login[username]" value="<?php echo $this->htmlEscape($this->getUsername()) ?>" >
    </p><!-- .form__field -->
    <p class="form__field">
        <label class="form__label"><?php echo $this->__('Password') ?></label>
        <input type="password" class="form__textfield textfield required-entry" id="login-password" name="login[password]">
        <?php echo $this->getChildHtml('form.additional.info'); ?>
    </p>
    <p class="form__submit-wrapper">
        <button type="submit" class="form__submit button sign-in" onclick="onepageLogin(this)"><?php echo $this->__('Sign in') ?></button>
        <button type="button" class="form__submit button new-account" onclick="<?php if($this->getQuote()->isAllowedGuestCheckout() ): ?>$('login:register').checked = true;setStepDescription('login', '');<?php endif;?>checkout.setMethod();"><?php echo $this->__('Create an account') ?></button>
    </p>
<?php if(!$this->getQuote()->isAllowedGuestCheckout() ): ?>
    <input type="hidden" name="checkout_method" id="login:register" value="register" checked="checked" />
<?php endif;?>
</form>
<?php if( $this->getQuote()->isAllowedGuestCheckout() ): ?>
    <input style="display:none;" type="radio" class="form__radio" name="checkout_method" id="login:guest" value="guest">
    <input style="display:none;" type="radio" class="form__radio" name="checkout_method" id="login:register" value="register">
    <h3 class="checkout-method__title guest">
        <?php echo $this->__('Checkout as Guest') ?>
    </h3>
    <p class="form__submit-wrapper">
        <button type="button" onclick="$('login:guest').checked = true;setStepDescription('login', '<?php echo $this->__('You are checking out as Guest')?>');checkout.setMethod();" class="form__submit button continue"><?php echo $this->__('Continue') ?></button>
    </p><!-- .form__submit-wrapper -->
<?php endif;?>
<script type="text/javascript">
    //<![CDATA[
    var loginForm = new VarienForm('checkout-login-form', true);
    $('login-email').observe('keypress', bindLoginPost);
    $('login-password').observe('keypress', bindLoginPost);
    function bindLoginPost(evt){
        if (evt.keyCode == Event.KEY_RETURN) {
            loginForm.submit();
        }
    }
    function onepageLogin(button)
    {
        if(loginForm.validator && loginForm.validator.validate()){
            button.disabled = true;
            loginForm.submit();
        }
    }
    Quo($('checkout_customer_forgot_form')).tap(function(e){
        window.customerAccount.showForgotForm();
        window.customerAccount.showMenu();
        Event.stop(e);
    });
    //]]>
</script>
<?php
$registerParam = $this->getRequest()->getParam('register');
if ($registerParam || $registerParam === ''):
    ?>
    <script type="text/javascript">
        //<![CDATA[
        document.observe("dom:loaded", function() {
            if($('login:register')) {
                $('login:register').checked = true;
                checkout.setMethod();
            }
        })
        //]]>
    </script>
<?php endif; ?>