<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Mobile2
 * @version    2.0.2
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><form action="" id="co-shipping-form">
    <?php if ($this->customerHasAddresses()): ?>
        <p class="form__field form__field--required">
            <label class="form__label">
                <?php echo $this->__('Select a shipping address from your address book or enter a new address.') ?>
            </label>
            <?php echo $this->getAddressesHtmlSelect('shipping') ?>
        </p><!-- .form__field -->
    <?php endif ?>
    <div id="shipping-new-address-form" <?php if ($this->customerHasAddresses()): ?> style="display:none;"<?php endif ?>>
        <input type="hidden" name="shipping[address_id]" value="<?php echo $this->getAddress()->getId() ?>" id="shipping:address_id" />
        <?php echo $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getAddress())->setFieldIdFormat('shipping:%s')->setFieldNameFormat('shipping[%s]')->setFieldParams('onchange="shipping.setSameAsBilling(false)"')->toHtml() ?></li>
        <p class="form__field">
            <label class="form__label" for="shipping:company"><?php echo $this->__('Company') ?></label>
            <input type="text" class="form__textfield textfield" id="shipping:company" name="shipping[company]" value="<?php echo $this->htmlEscape($this->getAddress()->getCompany()) ?>" onchange="shipping.setSameAsBilling(false);" title="<?php echo $this->__('Company') ?>">
        </p><!-- .form__field -->
        <p class="form__field form__field--required">
            <label for="shipping:street1" class="form__label form__label--required"><?php echo $this->__('Address') ?></label>
            <input type="text" class="form__textfield textfield required-entry" title="<?php echo $this->__('Street Address') ?>" name="shipping[street][]" id="shipping:street1" value="<?php echo $this->htmlEscape($this->getAddress()->getStreet(1)) ?>" onchange="shipping.setSameAsBilling(false);">
        </p><!-- .form__field -->
        <?php for ($_i=2, $_n=$this->helper('customer/address')->getStreetLines(); $_i<=$_n; $_i++): ?>
            <p class="form__field">
                <label class="form__label" for="shipping:street<?php echo $_i?>"><?php echo $this->__('Street Address %s', $_i) ?></label>
                <input type="text" class="form__textfield textfield" title="<?php echo $this->__('Street Address %s', $_i) ?>" name="shipping[street][]" id="shipping:street<?php echo $_i?>" value="<?php echo $this->htmlEscape($this->getAddress()->getStreet($_i)) ?>" onchange="shipping.setSameAsBilling(false);">
            </p><!-- .form__field -->
        <?php endfor ?>
        <p class="form__field form__field--required">
            <label class="form__label form__label--required"><?php echo $this->__('City') ?></label>
            <input type="text" class="form__textfield textfield required-entry" title="<?php echo $this->__('City') ?>" id="shipping:city" name="shipping[city]" value="<?php echo $this->htmlEscape($this->getAddress()->getCity()) ?>" onchange="shipping.setSameAsBilling(false);">
        </p><!-- .form__field -->
        <p class="form__field form__field--required">
            <label class="form__label form__label--required" for="shipping:region_id"><?php echo $this->__('State/Province') ?></label>
            <select class="form__select validate-select" id="shipping:region_id" name="shipping[region_id]" title="<?php echo $this->__('State/Province') ?>" style="display:none;">
                <option value=""><?php echo $this->__('Please select region, state or province') ?></option>
            </select>
            <script type="text/javascript">
                //<![CDATA[
                $('shipping:region_id').setAttribute('defaultValue',  "<?php echo $this->getAddress()->getRegionId() ?>");
                //]]>
            </script>
            <input type="text" id="shipping:region" name="shipping[region]" value="<?php echo $this->htmlEscape($this->getAddress()->getRegion()) ?>"  title="<?php echo $this->__('State/Province') ?>" class="form__textfield textfield" style="display:none;" />
        </p><!-- .form__field -->
        <p class="form__field form__field--required">
            <label for="shipping:postcode" class="form__label form__label--required"><?php echo $this->__('Zip/Postal Code') ?></label>
            <input type="text" class="form__textfield textfield required-entry" title="<?php echo $this->__('Zip/Postal Code') ?>" name="shipping[postcode]" id="shipping:postcode" value="<?php echo $this->htmlEscape($this->getAddress()->getPostcode()) ?>" onchange="shipping.setSameAsBilling(false);" />
        </p><!-- .form__field -->
        <p class="form__field form__field--required">
            <label class="form__label form__label--required" for="shipping:country_id"><?php echo $this->__('Country') ?></label>
            <?php echo $this->getCountryHtmlSelect('shipping') ?>
        </p><!-- .form__field -->
        <p class="form__field form__field--required">
            <label for="shipping:telephone" class="form__label form__label--required"><?php echo $this->__('Telephone') ?></label>
            <input type="tel" class="form__textfield textfield required-entry" name="shipping[telephone]" value="<?php echo $this->htmlEscape($this->getAddress()->getTelephone()) ?>" title="<?php echo $this->__('Telephone') ?>" id="shipping:telephone" onchange="shipping.setSameAsBilling(false);" />
        </p><!-- .form__field -->
        <p class="form__field">
            <label class="form__label" for="shipping:fax"><?php echo $this->__('Fax') ?></label>
            <input type="tel" id="shipping:fax" class="form__textfield textfield" name="shipping[fax]" value="<?php echo $this->htmlEscape($this->getAddress()->getFax()) ?>" title="<?php echo $this->__('Fax') ?>" onchange="shipping.setSameAsBilling(false);">
        </p><!-- .form__field -->
        <?php $addressAttributes = $this->getChild('customer_form_shipping_address_user_defined_attributes');?>
        <?php if ($addressAttributes && $addressAttributes instanceof Enterprise_Customer_Block_Form): ?>
            <?php $addressAttributes->setEntity($this->getAddress())->setEntityType('customer_address');?>
            <?php $addressAttributes->setFieldIdFormat('shipping:%1$s')->setFieldNameFormat('shipping[%1$s]');?>
            <?php echo $addressAttributes->setExcludeFileAttributes(true)->setShowContainer(false)->toHtml()?>
        <?php endif;?>
        <?php if ($this->isCustomerLoggedIn() && $this->customerHasAddresses()):?>
            <div class="form__field">
                <ul class="form__checkboxes">
                    <li class="form__checkboxes-item">
                        <input type="checkbox" name="shipping[save_in_address_book]" value="1" title="<?php echo $this->__('Save in address book') ?>" id="shipping:save_in_address_book" onchange="shipping.setSameAsBilling(false);"<?php if ($this->getAddress()->getSaveInAddressBook()):?> checked="checked"<?php endif;?> class="form__checkbox" />
                        <label class="form__checkbox-label" for="shipping:save_in_address_book"><?php echo $this->__('Save in address book') ?></label>
                    </li>
                </ul>
            </div>
        <?php else:?>
            <div class="no-display">
                <input type="hidden" name="shipping[save_in_address_book]" value="1" />
            </div>
        <?php endif; ?>
    </div>
    <div class="form__field" style="display:none;">
        <ul class="form__checkboxes">
            <li class="form__checkboxes-item">
                <input type="checkbox" name="shipping[same_as_billing]" id="shipping:same_as_billing" value="1"<?php if($this->getAddress()->getSameAsBilling()): ?> checked="checked"<?php endif; ?> title="<?php echo $this->__('Use Billing Address') ?>" onclick="shipping.setSameAsBilling(this.checked)" class="form__checkbox" />
                <label class="form__checkbox-label" for="shipping:same_as_billing">
                    <?php echo $this->__('Use Billing Address') ?>
                </label>
            </li>
        </ul>
    </div>
    <div>
        <p class="form__submit-wrapper" id="shipping-buttons-container">
            <button type="button" onclick="setStepDescription('shipping', getShippingStepDescription());shipping.save()" class="form__submit button continue"><?php echo $this->__('Continue') ?></button>
        </p><!-- .form__submit-wrapper -->
    </div>
</form>
<script type="text/javascript">
    //<![CDATA[
    var shipping = new Shipping('co-shipping-form', '<?php echo $this->getUrl('checkout/onepage/getAddress') ?>address/', '<?php echo $this->getUrl('checkout/onepage/saveShipping') ?>',
        '<?php echo $this->getUrl('checkout/onepage/shippingMethod') ?>');
    var shippingForm = new VarienForm('co-shipping-form');
    shippingForm.extraChildParams = ' onchange="shipping.setSameAsBilling(false);"';
    $('shipping-address-select') && shipping.newAddress(!$('shipping-address-select').value);
    var shippingRegionUpdater = new RegionUpdater('shipping:country_id', 'shipping:region', 'shipping:region_id', countryRegions, undefined, 'shipping:postcode');
    var getShippingStepDescription = function()
    {
        return '<p>'+$('shipping:firstname').value+' '+$('shipping:lastname').value+'</p>'
            + '<p>'+$('shipping:street1').value+','+'</p>'
            + '<p>'+$('shipping:telephone').value+'</p>'
            ;
    };
    $('co-shipping-form').select('.textfield').each(function(el){
        el.observe('keypress', function(e){
            if (e.keyCode !== 13) {
                return;
            }
            var nextFormField = el.up('.form__field').next('.form__field');
            if (nextFormField && nextFormField.down('.textfield')) {
                nextFormField.down('.textfield').focus();
            }
        });
    });
    //]]>
</script>