<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Mobile2
 * @version    2.0.2
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><form id="co-shipping-method-form" action="">
    <div class="form__field">
        <div class="shipping-methods" id="checkout-shipping-method-load">
            <?php echo $this->getChildHtml('available') ?>
        </div><!-- .shipping-methods -->
    </div><!-- .form__field -->
    <script type="text/javascript">
        //<![CDATA[
        var shippingMethod = new ShippingMethod('co-shipping-method-form', "<?php echo $this->getUrl('checkout/onepage/saveShippingMethod') ?>");
        var getShippingMethodStepDescription = function()
        {
            var result = '';
            $$('input[name="shipping_method"]').each(function(el){
                if(el.checked) {
                    result = eval('window.shippingLabels.' + el.value);
                }
            }.bind(result));
            return result;
        }
        //]]>
    </script>
    <div id="onepage-checkout-shipping-method-additional-load">
        <?php echo $this->getChildHtml('additional') ;?>
    </div>

    <p class="form__submit-wrapper" id="shipping-method-buttons-container">
        <button type="button" class="form__submit button continue" style="background-color:#F4A137" onclick="setStepDescription('shipping_method', getShippingMethodStepDescription());shippingMethod.save()"><?php echo $this->__('Choose and continue') ?></button>
    </p><!-- .form__submit-wrapper -->
</form>