<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Mobile2
 * @version    2.0.2
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><?php
    $arpBlock = $this->getLayout()->getBlock('awarp.content.instead.native');
    if ($arpBlock) {
        echo trim($arpBlock->toHtml());
    }
    $relatedBlock = $this->getLayout()->getBlock('catalog.product.related');
    if ($relatedBlock) {
        echo trim($relatedBlock->toHtml());
    }
    $upsellBlock = $this->getLayout()->getBlock('product.info.upsell');
    if ($upsellBlock) {
        echo trim($upsellBlock->toHtml());
    }
    $crosssellBlock = $this->getLayout()->getBlock('checkout.cart.crosssell');
    if ($crosssellBlock) {
        echo trim($crosssellBlock->toHtml());
    }
?>