<?php echo $this->getChildHtml('sticky.nav') ?>
<?php
    $store = Mage::app()->getStore();
    $code  = $store->getCode();
    $custom_block = Mage::getStoreConfig('porto_settings/header/static_block', $code);
?>
<div class="header-container type12">
    <div class="header">
        <div class="switcher-area">
            <?php echo $this->getChildHtml('store_currency'); ?>
            <?php echo $this->getChildHtml('store_language'); ?>
            <?php echo $this->getChildHtml('compare_link'); ?>
            <?php echo $this->getChildHtml('minicart'); ?>
        </div>
        <?php if ($this->getIsHomePage()):?>
        <h1 class="logo"><strong><?php echo $this->getLogoAlt(); ?></strong><a href="<?php echo $this->getUrl(''); ?>" title="<?php echo $this->getLogoAlt(); ?>" class="logo"><img src="<?php echo $this->getLogoSrc(); ?>" alt="<?php echo $this->getLogoAlt(); ?>" /></a></h1>
        <?php else:?>
        <a href="<?php echo $this->getUrl(''); ?>" title="<?php echo $this->getLogoAlt(); ?>" class="logo"><strong><?php echo $this->getLogoAlt(); ?></strong><img src="<?php echo $this->getLogoSrc(); ?>" alt="<?php echo $this->getLogoAlt(); ?>" /></a>
        <?php endif; ?>
        <?php echo $this->getChildHtml('topMenu') ?>
        <div class="mobile-group">
            <div class="search-area">
                <a href="javascript:void(0);" class="search-icon"><i class="icon-search"></i></a>
                <?php echo $this->getChildHtml('topSearch'); ?>
            </div>
            <div class="top-links-area">
                <div class="top-links-icon"><a href="javascript:void(0)"><?php echo $this->__("links"); ?></a></div>
                <?php echo $this->getChildHtml('topLinks'); ?>
            </div>
            <div class="menu-icon"><a href="javascript:void(0)"><i class="fa fa-bars"></i></a></div>
        </div>
        <div class="clearer"></div>
        <?php echo $this->getChildHtml('mobile.nav') ?>
        <?php
            $custom_block = Mage::getStoreConfig('porto_settings/header/static_block', $code);
        ?>
        <?php echo '<div class="custom-block">'.$this->getLayout()->createBlock('cms/block')->setBlockId($custom_block)->toHtml().'</div>'; ?>
    </div>
</div>