<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Mobile2
 * @version    2.0.2
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><?php /* @var $this Enterprise_GiftCard_Block_Catalog_Product_View_Type_Giftcard */?>
<?php $_product = $this->getProduct(); ?>
<?php echo $this->getPriceHtml($_product) ?>
<?php if ($_product->isAvailable()): ?>
    <p class="product-card__availability"><?php echo $this->__('Availability:') ?><?php echo $this->__('In stock') ?></p>
<?php else: ?>
    <p class="product-card__availability"><?php echo $this->__('Availability:') ?> <?php echo $this->__('Out of stock') ?></p>
<?php endif; ?>
<?php echo $this->getChildHtml('product_type_data_extra') ?>
