<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Mobile2
 * @version    2.0.2
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><?php
/**
 * Create account form template
 *
 * @see Enterprise_Customer_Block_Form_Renderer_Image
 */
/* @var $this Enterprise_Rma_Block_Form_Renderer_Image */
?>
<p class="form__field <?php if ($this->isRequired()) echo 'form__field--required' ?>">
    <label for="items:<?php echo $this->getHtmlId()?>_index_" class="form__label <?php if ($this->isRequired()) echo 'form__label--required' ?>"><?php echo $this->getLabel() ?></label>
    <input type="file" id="items:<?php echo $this->getHtmlId()?>_index_" name="<?php echo $this->getFieldName()?>__index_" value="" class="input-file" />
    <input type="hidden" id="items:<?php echo $this->getHtmlId()?>_index__value" value="<?php echo $this->getEscapedValue()?>" <?php if ($this->isRequired()): ?>class="required-entry" <?php endif;?>/>
    <script type="text/javascript">
        //<![CDATA[
        new Varien.FileElement('items:<?php echo $this->getHtmlId()?>_index_');
        //]]>
    </script>
</p>