<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Mobile2
 * @version    2.0.2
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><div class="contacts">
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <form action="<?php echo $this->getFormAction(); ?>" id="contactForm" method="post" class="form">
        <div class="fieldset">
            <p class="required">
                <?php echo $this->__('Required Fields') ?>
            </p>
            <p class="form__field form__field--required">
                <label for="name" class="form__label form__label--required"><?php echo Mage::helper('contacts')->__('Name') ?></label>
                <input name="name" id="name" title="<?php echo Mage::helper('contacts')->__('Name') ?>" value="<?php echo $this->htmlEscape($this->helper('contacts')->getUserName()) ?>" class="form__textfield textfield required-entry" type="text" />
            </p>
            <p class="form__field form__field--required">
                <label for="email" class="form__label form__label--required"><?php echo $this->__('Email Address') ?></label>
                <input type="email" class="form__textfield textfield validate-email required-entry" name="email" id="email_address" value="<?php echo $this->htmlEscape($this->helper('contacts')->getUserEmail()) ?>" title="<?php echo Mage::helper('contacts')->__('Email') ?>">
            </p><!-- .form__field -->
            <p class="form__field">
                <label for="telephone" class="form__label "><?php echo Mage::helper('contacts')->__('Telephone') ?></label>
                <input name="telephone" id="telephone" title="<?php echo Mage::helper('contacts')->__('Telephone') ?>" value="" class="form__textfield textfield" type="text" />
            </p>
            <p class="form__field form__field--required">
                <label for="comment" class="form__label form__label--required"><?php echo Mage::helper('contacts')->__('Comment') ?></label>
                <textarea name="comment" id="comment" title="<?php echo Mage::helper('contacts')->__('Comment') ?>" value="<?php echo $this->htmlEscape($this->helper('contacts')->getUserName()) ?>" class="form__textfield textfield required-entry" cols="5" rows="3"></textarea>
            </p>
        </div>
        <p class="form__submit-wrapper">
            <input type="text" name="hideit" id="hideit" value="" style="display:none !important;" />
            <button type="submit" title="<?php echo Mage::helper('contacts')->__('Submit') ?>" class="form__submit button continue"><?php echo Mage::helper('contacts')->__('Submit') ?></button>
        </p><!-- .form__submit-wrapper -->
    </form>
    <script type="text/javascript">
        //<![CDATA[
        var contactForm = new VarienForm('contactForm', true);
        //]]>
    </script>
</div>