<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Mobile2
 * @version    2.0.2
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><header class="panel-nav" id="my_account">
	<a href="javascript:history.back();" title="<?php echo $this->htmlEscape($firstLink['title']) ?>" class="page-header__action page-header__action--left page-header__action--back">
            	<span class="page-header__action--back" style="font-size:24px">&lt;</span>
        	</a>
    <h2 class="panel-nav__title" data-default-title="<?php echo $this->__('My Account');?>">
        <span class="active"><?php echo $this->__('My Account')?></span>
    </h2>
    <button type="button" class="panel-nav__action panel-nav__action--right panel-nav__action--cancel not-lap-land js-close-panel">
    </button>
</header>
<div class="my-account panel__container">
	<!--<div class="panel-order">
    	<div class="panel_order_top">
        	已登录状态显示
        	<div class="panel_loginin">
            	<div class="panel_loginin_img"><img ></div>
            	<div class="panel_loginin_name">firstname lastname</div>
           	</div>
            未登录状态显示
        	<div class="panel_loginout">
            	<button class="panel_loginout_l">Register</button>
                <button class="panel_loginout_r">Login</button>
            </div>
        </div>
        <div class="panel_order_bottom">
        	<ul>
            	<li>Pending</li>
                <li>Shipping</li>
                <li>All</li>
            </ul>
        </div>
    </div>-->
    <div class="my-account__container-inner">
        <ul class="my-account-nav">
            <?php foreach ($this->getLinks() as $_link): ?>
                <li class="my-account-nav__item <?php if ($this->isActive($_link)): ?>is-current<?php endif;?>"><a class="my-account-nav__link" href="<?php if ($this->isActive($_link)) echo 'javascript:void(0);'?><?php if (!$this->isActive($_link)) echo $_link->getUrl()?>"><?php echo $_link->getLabel() ?></a></li>
            <?php endforeach;?>
            <li class="my-account-nav__item"><a class="my-account-nav__link logout" href="<?php echo $this->helper('customer')->getLogoutUrl();?>"><?php echo $this->__("Logout");?></a></li>
        </ul>
    </div><!-- .nav__list -->
</div>
<script>
	jQuery(function(){
			jQuery(window).load(function(){
					var r_url = document.referrer;
					if(r_url.indexOf("skymazon.sunpop.cn") > 0){
							jQuery("#my_account .js-close-panel").show();
							jQuery("#my_account .page-header__action--back").hide();
							console.log("yes");
						}
					else{
							jQuery("#my_account .js-close-panel").hide().remove();
							jQuery("#my_account .page-header__action--back").show();
							console.log("no");
						}
				});
		})
</script>