<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Mobile2
 * @version    2.0.2
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><?php if ($this->canShow() && $this->getEvents() && count($this->getEvents())): ?>
    <div class="island">
        <h2 class="island-title"><?php echo Mage::helper('enterprise_customerbalance')->__('Balance History'); ?></h2>
        <table id="customerbalance-history" class="data-table">
            <thead>
            <tr class="data-table-row">
                <th><?php echo Mage::helper('enterprise_customerbalance')->__('Action'); ?></th>
                <th><?php echo Mage::helper('enterprise_customerbalance')->__('Balance Change'); ?></th>
                <th><?php echo Mage::helper('enterprise_customerbalance')->__('Balance'); ?></th>
                <th><?php echo Mage::helper('enterprise_customerbalance')->__('Date'); ?></th>
            </tr>
            </thead>
            <?php foreach ($this->getEvents() as $event): ?>
                <tbody>
                <tr class="data-table-row">
                    <td><?php echo $this->getActionLabel($event->getAction()); ?></td>
                    <td><?php echo Mage::helper('core')->currency($event->getBalanceDelta()); ?></td>
                    <td><?php echo Mage::helper('core')->currency($event->getBalanceAmount()); ?></td>
                    <td><?php echo Mage::helper('core')->formatDate($event->getUpdatedAt(), 'short', true); ?></td>
                </tr>
                </tbody>
            <?php endforeach; ?>
        </table>
    </div>
<?php endif; ?>
