<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Mobile2
 * @version    2.0.2
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><?php $_code=$this->getMethodCode() ?>
<div class="form-list" id="payment_form_<?php echo $_code ?>" style="display:none;">
    <p class="form__field">
        <label for="<?php echo $_code ?>_cc_type" class="form__label"><?php echo $this->__('Credit Card Type') ?></label>
        <select class="form__select required-entry validate-cc-type-select" id="<?php echo $_code ?>_cc_type" name="payment[cc_type]">
            <option value=""><?php echo $this->__('--Please Select--')?></option>
            <?php $_ccType = $this->getInfoData('cc_type') ?>
            <?php foreach ($this->getCcAvailableTypes() as $_typeCode => $_typeName): ?>
                <option value="<?php echo $_typeCode ?>"<?php if($_typeCode==$_ccType): ?> selected="selected"<?php endif ?>><?php echo $_typeName ?></option>
            <?php endforeach ?>
        </select>
    </p><!-- .form__field -->

    <p class="form__field">
        <label for="<?php echo $_code ?>_cc_number" class="form__label"><?php echo $this->__('Card Number') ?><span class="step-comment"><?php echo $this->__('The long number on your card')?></span></label>
        <input type="tel" id="<?php echo $_code ?>_cc_number" name="payment[cc_number]" title="<?php echo $this->__('Credit Card Number') ?>" class="form__textfield textfield required-entry validate-cc-number validate-cc-type" value="" />
    </p>
    <p class="form__field" id="<?php echo $_code ?>_cc_type_exp_div">
        <label for="<?php echo $_code ?>_expiration" class="form__label"><?php echo $this->__('Expiration Date') ?><span class="step-comment"><?php echo $this->__('Expiration mouth and year')?></span></label>
        <select id="<?php echo $_code ?>_expiration" name="payment[cc_exp_month]" class="form__select month validate-cc-exp required-entry">
            <?php $_ccExpMonth = $this->getInfoData('cc_exp_month') ?>
            <?php foreach ($this->getCcMonths() as $k=>$v): ?>
                <option value="<?php echo $k?$k:'' ?>"<?php if($k==$_ccExpMonth): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
            <?php endforeach ?>
        </select>
        <?php $_ccExpYear = $this->getInfoData('cc_exp_year') ?>
        <select id="<?php echo $_code ?>_expiration_yr" name="payment[cc_exp_year]" class="form__select year required-entry">
            <?php foreach ($this->getCcYears() as $k=>$v): ?>
                <option value="<?php echo $k?$k:'' ?>"<?php if($k==$_ccExpYear): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
            <?php endforeach ?>
        </select>
    </p>
    <?php echo $this->getChildHtml() ?>
    <?php if($this->hasVerification()): ?>
        <p id="<?php echo $_code ?>_cc_type_cvv_div" class="form__field">
            <label for="<?php echo $_code ?>_cc_cid" class="form__label"><?php echo $this->__('CVV') ?><span class="step-comment"><?php echo $this->__('The 3/4 digit security code on your card')?></span></label>
            <input type="tel" title="<?php echo $this->__('Card Verification Number') ?>" class="form__textfield textfield cvv required-entry validate-cc-cvn" id="<?php echo $_code ?>_cc_cid" name="payment[cc_cid]" value="" />
        </p>
    <?php endif; ?>

    <?php if ($this->hasSsCardType()): ?>
        <div id="<?php echo $_code ?>_cc_type_ss_div">
            <p class="form__field">
                <label for="<?php echo $_code ?>_cc_issue" class="form__label"><?php echo $this->__('Switch/Solo Only') ?></label></li>
            </p>
            <p class="form__field">
                <label class="form__label" for="<?php echo $_code ?>_cc_issue"><?php echo $this->__('Issue Number') ?>:</label>
                <input type="tel" title="<?php echo $this->__('Issue Number') ?>" class="form__textfield textfield validate-cc-ukss cvv" id="<?php echo $_code ?>_cc_issue" name="payment[cc_ss_issue]" value="" />
            </p>
            <p class="form__field">
                <label class="form__label" for="<?php echo $_code ?>_start_month"><?php echo $this->__('Start Date') ?>:</label>
                <select id="<?php echo $_code ?>_start_month" name="payment[cc_ss_start_month]" class="form__select validate-cc-ukss month">
                    <?php foreach ($this->getCcMonths() as $k=>$v): ?>
                        <option value="<?php echo $k?$k:'' ?>"<?php if($k==$this->getInfoData('cc_ss_start_month')): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                    <?php endforeach ?>
                </select>
                <select id="<?php echo $_code ?>_start_year" name="payment[cc_ss_start_year]" class="form__select validate-cc-ukss year">
                    <?php foreach ($this->getSsStartYears() as $k=>$v): ?>
                        <option value="<?php echo $k?$k:'' ?>"<?php if($k==$this->getInfoData('cc_ss_start_year')): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                    <?php endforeach ?>
                </select>
            </p>
            <span class="adv-container">&nbsp;</span>
            <script type="text/javascript">
                //<![CDATA[
                var SSChecked<?php echo $_code ?> = function() {
                    var elm = $('<?php echo $_code ?>_cc_type');
                    if (['SS','SM','SO'].indexOf(elm.value) != -1) {
                        $('<?php echo $_code ?>_cc_type_ss_div').show();
                    } else {
                        $('<?php echo $_code ?>_cc_type_ss_div').hide();
                    }
                };

                Event.observe($('<?php echo $_code ?>_cc_type'), 'change', SSChecked<?php echo $_code ?>);
                SSChecked<?php echo $_code ?>();

                Validation.addAllThese([
                    ['validate-cc-ukss', 'Please enter issue number or start date for switch/solo card type.', function(v,elm) {
                        var endposition;

                        if (elm.id.match(/(.)+_cc_issue$/)) {
                            endposition = elm.id.indexOf('_cc_issue');
                        } else if (elm.id.match(/(.)+_start_month$/)) {
                            endposition = elm.id.indexOf('_start_month');
                        } else {
                            endposition = elm.id.indexOf('_start_year');
                        }

                        var prefix = elm.id.substr(0,endposition);

                        var ccTypeContainer = $(prefix + '_cc_type');

                        if (!ccTypeContainer) {
                            return true;
                        }
                        var ccType = ccTypeContainer.value;

                        if(['SS','SM','SO'].indexOf(ccType) == -1){
                            return true;
                        }

                        $(prefix + '_cc_issue').advaiceContainer
                            = $(prefix + '_start_month').advaiceContainer
                            = $(prefix + '_start_year').advaiceContainer
                            = $(prefix + '_cc_type_ss_div').down('ul li.adv-container');

                        var ccIssue   =  $(prefix + '_cc_issue').value;
                        var ccSMonth  =  $(prefix + '_start_month').value;
                        var ccSYear   =  $(prefix + '_start_year').value;

                        var ccStartDatePresent = (ccSMonth && ccSYear) ? true : false;

                        if (!ccStartDatePresent && !ccIssue){
                            return false;
                        }
                        return true;
                    }]
                ]);
                //]]>
            </script>
        </div>
    <?php endif; ?>
</div>