<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Mobile2
 * @version    2.0.2
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><?php $_code=$this->getMethodCode() ?>
<div class="form-list" id="payment_form_<?php echo $_code ?>" style="display:none;">
    <p class="form__field">
        <label for="<?php echo $_code ?>_cc_owner" class="form__label"><?php echo $this->__('Name on Card') ?></label>
        <input type="text" title="<?php echo $this->__('Name on Card') ?>" class="form__textfield textfield required-entry" id="<?php echo $_code ?>_cc_owner" name="payment[cc_owner]" value="<?php echo $this->htmlEscape($this->getInfoData('cc_owner')) ?>" />
    </p>
    <p class="form__field">
        <label for="<?php echo $_code ?>_cc_type" class="form__label"><?php echo $this->__('Credit Card Type') ?></label>
        <select id="<?php echo $_code ?>_cc_type" name="payment[cc_type]" title="<?php echo $this->__('Credit Card Type') ?>" class="form__select required-entry validate-cc-type-select">
            <option value=""><?php echo $this->__('--Please Select--') ?></option>
            <?php $_ccType = $this->getInfoData('cc_type') ?>
            <?php foreach ($this->getCcAvailableTypes() as $_typeCode => $_typeName): ?>
                <option value="<?php echo $_typeCode ?>"<?php if($_typeCode==$_ccType): ?> selected="selected"<?php endif ?>><?php echo $_typeName ?></option>
            <?php endforeach ?>
        </select>
    </p>
    <p class="form__field">
        <label for="<?php echo $_code ?>_cc_number" class="form__label"><?php echo $this->__('Card Number') ?><span class="step-comment"><?php echo $this->__('The long number on your card')?></span></label>
        <input type="tel" id="<?php echo $_code ?>_cc_number" name="payment[cc_number]" title="<?php echo $this->__('Credit Card Number') ?>" class="form__textfield textfield validate-cc-number validate-cc-type" value="" />
    </p>
    <p class="form__field">
        <label for="<?php echo $_code ?>_expiration" class="form__label"><?php echo $this->__('Expiration Date') ?><span class="step-comment"><?php echo $this->__('Expiration mouth and year')?></span></label>
        <select id="<?php echo $_code ?>_expiration" name="payment[cc_exp_month]" class="form__select month validate-cc-exp required-entry">
            <?php $_ccExpMonth = $this->getInfoData('cc_exp_month') ?>
            <?php foreach ($this->getCcMonths() as $k=>$v): ?>
                <option value="<?php echo $k?$k:'' ?>"<?php if($k==$_ccExpMonth): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
            <?php endforeach ?>
        </select>
        <?php $_ccExpYear = $this->getInfoData('cc_exp_year') ?>
        <select id="<?php echo $_code ?>_expiration_yr" name="payment[cc_exp_year]" class="form__select year required-entry">
            <?php foreach ($this->getCcYears() as $k=>$v): ?>
                <option value="<?php echo $k?$k:'' ?>"<?php if($k==$_ccExpYear): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
            <?php endforeach ?>
        </select>
    </p>
    <?php echo $this->getChildHtml() ?>
    <?php if($this->hasVerification()): ?>
        <p class="form__field">
            <label for="<?php echo $_code ?>_cc_cid" class="form__label"><?php echo $this->__('CVV') ?><span class="step-comment"><?php echo $this->__('The 3/4 digit security code on your card')?></span></label>
            <input type="tel" title="<?php echo $this->__('Card Verification Number') ?>" class="form__textfield textfield cvv required-entry validate-cc-cvn" id="<?php echo $_code ?>_cc_cid" name="payment[cc_cid]" value="" />
        </p>
    <?php endif; ?>
</div>