<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Mobile2
 * @version    2.0.2
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><?php
/**
 * @see Enterprise_GiftCardAccount_Block_Checkout_Cart_Giftcardaccount
 */
?>
<div class="discount__field giftcard">
    <div id="giftcard_balance_lookup"></div>
    <form id="giftcard-form" action="<?php echo $this->getUrl('enterprise_giftcardaccount/cart/add') ?>" method="post" class="form">
        <label class="discount__field-label"><?php echo $this->__("Enter the gift card code")?></label>
        <input type="text" class="required-entry discount__textfield textfield" id="giftcard_code" name="giftcard_code" value="">
        <p class="discount__submit-wrapper">
            <button class="discount__submit js-apply-discount" onclick="window.giftcardForm.submit()" type="button" value="<?php echo $this->__('Add Gift Card') ?>"><?php echo $this->__('Add Gift Card') ?></button>
            <button class="discount__submit js-apply-discount check-gc-status" onclick="window.checkGiftCardStatus();" type="button" value="<?php echo $this->__('Check Gift Card status and balance') ?>"><?php echo $this->__('Check Gift Card status and balance') ?></button>
        </p>
    </form>

    <script type="text/javascript">
        window.giftcardForm = new VarienForm('giftcard-form');
        window.checkGiftCardStatus = function()
        {
            if (window.giftcardForm.validator && !window.giftcardForm.validator.validate()) {
                return false;
            }
            new Ajax.Updater(
                'giftcard_balance_lookup',
                '<?php echo Mage::getUrl('enterprise_giftcardaccount/cart/quickCheck') ?>',
                {
                    onCreate: function() { $('ajax_loader').show(); },
                    onComplete: function() { $('ajax_loader').hide(); },
                    parameters : {giftcard_code : $('giftcard_code').value}
                }
            );
        }
    </script>
</div>
