<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Mobile2
 * @version    2.0.2
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><?php
/**
 * @see Enterprise_GiftCardAccount_Block_Check
 */
?>
<div class="giftcard-status">
    <div class="page-title">
        <h1><?php echo Mage::helper('enterprise_giftcardaccount')->__('Gift Card status'); ?></h1>
    </div>

<?php if ($this->getCode()): ?>
    <?php echo $this->getChildHtml('check_result') ?>
<?php endif; ?>
    <form method="post" id="codeForm">
        <fieldset>
            <ul class="form-list">
                <li>
                    <label for="code"><?php echo Mage::helper('enterprise_giftcardaccount')->__('Enter Gift Card code'); ?></label>
                    <div class="input-box">
                        <input type="text" class="input-text required-entry" name="giftcard_code" id="code" value="<?php echo $this->htmlEscape($this->getCode()) ?>" />
                    </div>
                </li>
            </ul>
        </fieldset>
        <div class="buttons-set form-buttons btn-only">
             <button class="button" type="button" onclick="cForm.submit()"><?php echo Mage::helper('enterprise_giftcardaccount')->__('Check'); ?></button>
        </div>
    </form>
    <script type="text/javascript">
    var cForm = new VarienForm('codeForm');
    </script>
</div>
