<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Mobile2
 * @version    2.0.2
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><?php if($crumbs && is_array($crumbs)): ?>
<?php foreach($crumbs as $_crumbInfo): ?>
    <?php if (!$_crumbInfo['last']):?>
        <?php $firstLink = $_crumbInfo;?>
    <?php else:?>
            <?php $lastLink = $_crumbInfo;?>
    <?php endif; ?>
<?php endforeach; ?>
<header id="breadcrumbs" class="page-header">
    <?php if(!Mage::registry('is_home_page_flag')):?>
        <a href="javascript:history.back();" title="<?php echo $this->htmlEscape($firstLink['title']) ?>" class="page-header__action page-header__action--left page-header__action--back">
            <?php //echo $this->htmlEscape($firstLink['label']) ?>
        </a>
    <?php endif;?>
    <h1 id="breadcrumbs_page_title" class="page-header__title">
        <?php //echo $this->htmlEscape($lastLink['label']) ?>
    </h1>
</header><!-- .page-header -->
<script type="text/javascript">
    setTitleMargin($('breadcrumbs_page_title'));
</script>
<?php else:?>
    <?php $headBlock = $this->getLayout()->getBlock('head');?>
    <header id="breadcrumbs" class="page-header">
        <?php if(!Mage::registry('is_home_page_flag')):?>
            <a href="javascript:history.back();" title="<?php echo $this->__('Home') ?>" class="page-header__action page-header__action--left page-header__action--back">
                <?php //echo $this->htmlEscape($firstLink['label']) ?>
            </a>
        <?php endif;?>
        <h1 id="breadcrumbs_page_title" class="page-header__title">
            <?php echo $headBlock ? $this->htmlEscape($headBlock->getTitle()) : '' ?>
        </h1>
    </header>
<?php endif; ?>