<?php ?><header id="top_header" class="header">
<ul class="header__nav">
    <li class="header__nav-item">
        <a href="javascript:void(0)" id="customer_account_link" class="header__link header__link--user js-open-panel">
            <?php echo $this->__('User')?>
        </a>
    </li>
    <li class="header__nav-item">
        <?php $summaryQty = (int)Mage::getSingleton('checkout/cart')->getSummaryQty();?>
        <a id="shopping_cart" href="javascript:void(0)" class="header__link header__link--cart<?php echo ($summaryQty == 0)?" header__link--cart-empty":"";?>">
            <?php if ($summaryQty > 0):?>
                <span class="items-in-cart"><?php echo $summaryQty;?></span>
            <?php endif;?>
        </a>
    </li>
</ul>
</header><?php ?>
