<?php /*?><header id="top_header" class="header">
<p class="logo">
    <a href="<?php echo $this->getUrl('') ?>" class="logo__link">
        <img src="<?php echo AW_Mobile2_Helper_Config::getMobileLogoSrc() ? AW_Mobile2_Helper_Config::getMobileLogoSrc() : $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>" class="logo__image">
    </a>
</p>
<ul class="header__nav">
    <li class="header__nav-item"><a href="javascript:void(0);" id="navigation_link" class="header__link header__link--catalog js-open-panel"><?php echo $this->__('Catalog')?></a></li>
    <?php if ($searchLink = $this->getChildHtml('catalog_search_link')):?>
    <li class="header__nav-item" style="float:left">
        <?php echo $searchLink;?>
    </li>
    <?php endif;?>
    <li class="header__nav-item">
        <?php $summaryQty = (int)Mage::getSingleton('checkout/cart')->getSummaryQty();?>
        <a id="shopping_cart" href="javascript:void(0)" class="header__link header__link--cart<?php echo ($summaryQty == 0)?" header__link--cart-empty":"";?>">
            <?php if ($summaryQty > 0):?>
                <span class="items-in-cart"><?php echo $summaryQty;?></span>
            <?php endif;?>
        </a>
    </li>
    <li class="header__nav-item">
        <a href="javascript:void(0)" id="customer_account_link" class="header__link header__link--user js-open-panel">
            <?php echo $this->__('User')?>
        </a>
    </li>
</ul>
</header><?php */?>
