<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Mobile2
 * @version    2.0.2
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><p class="more"><a class="more__button" id="pager_button" href="javascript:void(0);"><?php echo $this->__('Show %s more', $this->getLimit());?></a></p>
<script type="text/javascript">
    //<![CDATA[
    if (typeof window.pager == 'undefined') {
        window.pager = new awMobile2.app.pager('pager_button', <?php echo $this->getCurrentPage()?>, <?php echo $this->getLastPageNum()?>);
    } else {
        window.pager.reInit(<?php echo $this->getCurrentPage()?>, <?php echo $this->getLastPageNum()?>);
    }
    //]]>
</script>