<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Mobile2
 * @version    2.0.2
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><div class="paypal-express-review">
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <div class="islands">
        <?php if ($this->getShippingAddress()):?>
            <div class="island">
                <h2 class="checkout-step__title step-title"><?php echo $this->__('Shipping Information') ?></h2>
                <div>
                    <h3>
                        <?php echo $this->__('Shipping Address') ?>
                        <span class="separator">
                    <?php if ($this->getCanEditShippingAddress()):?> |
                        </span><a href="<?php echo $this->getEditUrl() ?>"><?php echo $this->__('Change Shipping Address') ?></a>
                    <?php endif;?>
                    </h3>
                    <address><?php echo $this->renderAddress($this->getShippingAddress())?></address>
                </div>
                <div>
                    <h3><?php echo $this->__('Shipping Method') ?></h3>
                    <?php if ($this->getCanEditShippingMethod() || !$this->getCurrentShippingRate()):?>
                        <?php if ($groups = $this->getShippingRateGroups()):?>
                            <?php $currentRate = $this->getCurrentShippingRate(); ?>
                            <form method="post" id="shipping_method_form" class="form" action="<?php echo $this->escapeHtml($this->getShippingMethodSubmitUrl()) ?>">
                                <p class="form__field form__field--required">
                                    <select name="shipping_method" id="shipping_method" class="form__select required-entry">
                                        <?php if (!$currentRate):?>
                                            <option value=""><?php echo $this->__('Please select a shipping method...') ?></option>
                                        <?php endif;?>
                                        <?php foreach ($groups as $code => $rates):?>
                                            <optgroup label="<?php echo $this->getCarrierName($code) ?>" style="font-style:normal;">
                                                <?php foreach ($rates as $rate):?>
                                                    <option value="<?php echo $this->renderShippingRateValue($rate)?>"<?php echo ($currentRate === $rate) ? ' selected="selected"' : '' ;?>>
                                                        <?php echo $this->renderShippingRateOption($rate)?>
                                                    </option>
                                                <?php endforeach;?>
                                            </optgroup>
                                        <?php endforeach;?>
                                    </select>
                                </p>
                                <p class="form__submit-wrapper">
                                    <button id="update_shipping_method_submit" type="submit" class="form__submit button"><?php echo $this->__('Update Shipping Method') ?></button>
                                </p>
                            </form>
                        <?php else: ?>
                            <p><?php echo $this->__('Sorry, no quotes are available for this order at this time.') ?></p>
                        <?php endif;?>
                    <?php else: ?>
                        <p><?php echo $this->renderShippingRateOption($this->getCurrentShippingRate())?></p>
                    <?php endif; ?>
                </div>
            </div>
        <?php endif;?>
        <div class="island">
            <h2 class="checkout-step__title"><?php echo $this->__('Billing Information') ?></h2>
            <div>
                <h3><?php echo $this->__('Payment Method') ?> <span class="separator">|</span> <a href="<?php echo $this->getEditUrl() ?>"><?php echo $this->__('Change Payment Method') ?></a></h3>
                <?php echo $this->escapeHtml($this->getPaymentMethodTitle()) ?>
            </div>
            <div>
                <h3><?php echo $this->__('Billing Address') ?></h3>
                <address>
                    <?php echo $this->renderAddress($this->getBillingAddress()) ?><br />
                    <?php echo $this->__('Payer Email: %s', $this->getBillingAddress()->getEmail()) ?>
                </address>
            </div>
        </div>
        <div class="island">
            <h3 class="checkout-step__title"><?php echo $this->__('Items in Your Shopping Cart') ?><span class="separator"> | </span><a href="<?php echo $this->getUrl('checkout/cart') ?>"><?php echo $this->__('Edit Shopping Cart') ?></a></h3>
            <div>
                <?php echo $this->getChildHtml('details') ?>
            </div>
            <form class="form" method="post" id="order_review_form" action="<?php echo $this->getPlaceOrderUrl() ?>">
                <?php echo $this->getChildHtml('agreements'); ?>
                <p class="form__submit-wrapper" id="review-buttons-container">
                    <button id="review_button" value="<?php echo $this->__('Place Order') ?>" class="form__submit button"><?php echo $this->__('Place Order') ?></button>
                    <button type="submit" id="review_submit" value="<?php echo $this->__('Place Order') ?>" class="form__submit button"><?php echo $this->__('Place Order') ?></button>
                    <span class="loader" id="review-please-wait" style="display:none;"></span>
                </p>
            </form>
        </div>
    </div>
    <script type="text/javascript">
        //<![CDATA[
        // submit buttons are not needed when submitting with ajax
        $('review_submit').hide();
        if ($('update_shipping_method_submit')) {
            $('update_shipping_method_submit').hide();
        }

        PayPalExpressAjax = new OrderReviewController($('order_review_form'), $('review_button'),
            $('shipping_method'), $('shipping_method_form'), 'details-reload'
        );
        PayPalExpressAjax.addPleaseWait($('review-please-wait'));
        //]]>
    </script>
</div>