<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Mobile2
 * @version    2.0.2
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><?php
/**
 * @see Enterprise_Reward_Block_Customer_Reward_History
 */
?>
<div class="reward-history island" id="reward_history">
    <h2 class="island-title"><?php echo $this->__('Balance History'); ?></h2>
    <?php if ($history = $this->getHistory()):?>
        <table id="reward_history_data" class="data-table">
            <thead>
            <tr class="data-table-row">
                <th><?php echo $this->__('Balance'); ?></th>
                <th><?php echo $this->__('Amount'); ?></th>
                <th><?php echo $this->__('Points'); ?></th>
                <th><?php echo $this->__('Reason'); ?></th>
                <th><?php echo $this->__('Date'); ?></th>
            </tr>
            </thead>
            <tbody>
            <?php foreach($history as $item): ?>
                <tr class="data-table-row">
                    <td><?php echo $this->getPointsBalance($item)?></td>
                    <td><?php echo $this->getCurrencyBalance($item)?></td>
                    <td><?php echo $this->getPointsDelta($item)?></td>
                    <td>
                        <?php echo $this->escapeHtml($this->getMessage($item))?>
                        <?php if ($explanation = $this->getExplanation($item)):?><br /><small><?php echo $this->escapeHtml($explanation);?></small><?php endif;?>
                    </td>
                    <td>
                        <span class="nobr"><?php echo $this->getDate($item)?></span>
                        <?php if ($expirationDate = $this->getExpirationDate($item)):?>
                            <small class="nobr"><?php echo $this->__('Expires on %s', $expirationDate);?></small>
                        <?php endif;?>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    <?php else:?>
        <p><?php echo $this->__('There is no balance history yet.')?></p>
    <?php endif;?>
</div>
<?php echo $this->getChildHtml('pager') ?>
<script type="text/javascript">
    //<![CDATA[
    if (typeof pager != 'undefined') {
        pager.containerId = 'reward_history';
        pager.tableId = 'reward_history_data';
    }
    //]]>
</script>