<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Mobile2
 * @version    2.0.2
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><?php
/**
 * @see Enterprise_Reward_Block_Customer_Reward_Info
 */
?>
<?php
$helper = Mage::helper('enterprise_reward');
$maxBalance = $this->getMaxBalance();
$minBalance = $this->getMinBalance();
$expireIn = $this->getExpireIn();
?>
<div class="island">
    <h2 class="island-title"><?php echo $this->__('Reward points balance Information'); ?> <span class="separator">|</span> <a href="<?php echo $helper->getLandingPageUrl()?>"><?php echo $this->__('Learn more...')?></a></h2>
    <dl class="box-content">
        <dt><?php echo $this->__('Your current balance is %s.', $helper->formatReward($this->getPointsBalance(), $this->getCurrencyBalance()))?></dt>
        <dt><?php echo $this->__('Current exchange rates:')?></dt>
        <?php if ($this->getPtsToAmountRateAmount() || $this->getAmountToPtsRatePts()): ?>
            <?php if ($this->getPtsToAmountRateAmount()): ?>
                <dd><?php echo $this->__('Each %s can be redeemed for %s.', $helper->formatReward($this->getPtsToAmountRatePts(), null, null, '<strong>%s</strong>'), '<strong>' . $helper->formatAmount($this->getPtsToAmountRateAmount()) . '</strong>')?></dd>
            <?php endif;?>
            <?php if ($this->getAmountToPtsRatePts()): ?>
                <dd><?php echo $this->__('Each %s spent will earn %s.', '<strong>' . $helper->formatAmount($this->getAmountToPtsRateAmount()) . '</strong>', $helper->formatReward($this->getAmountToPtsRatePts(), null, null, '<strong>%s</strong>'))?></dd>
            <?php endif;?>
        <?php else:?>
            <dd><?php echo $this->__('None.')?></dd>
        <?php endif;?>
        <?php if ($maxBalance || $minBalance):?>
            <dt><?php echo $this->__('Balance limitations:')?></dt>
            <?php if ($maxBalance):?>
                <dd><?php echo $this->__('Balance is capped at %s.', $helper->formatReward($maxBalance))?></dd>
                <?php if ($this->getIsMaxBalanceReached()):?>
                    <dd class="warning"><?php echo $this->__('Maximum balance is reached.')?></dd>
                <?php endif;?>
            <?php endif;?>
            <?php if ($minBalance):?>
                <dd><?php echo $this->__('Minimum Balance in order to redeem: %s.', $helper->formatReward($minBalance))?></dd>
                <?php if (!$this->getIsMinBalanceReached()):?>
                    <dd class="warning"><?php echo $this->__('Minimum balance for redeeming points is not reached.')?></dd>
                <?php endif;?>
            <?php endif;?>
        <?php endif;?>
        <?php if ($expireIn):?>
            <dt><?php echo $this->__('Each earned reward points record expires in %s days.', '<span>' . $expireIn . '</span>')?></dt>
            <?php if ($this->getIsHistoryPublished()):?>
                <dd><?php echo $this->__('Refer to reward points history to see if a specific record expires and when.')?></dd>
            <?php endif;?>
        <?php endif;?>
    </dl>
</div>