<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Mobile2
 * @version    2.0.2
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><?php
/* @var $this Mage_Core_Block_Template */
/* @var $catalogSearchHelper Mage_Catalogsearch_Helper_Data */
$catalogSearchHelper =  $this->helper('catalogsearch');
?>
<div class="search-container popup-form">
    <header class="panel-nav">
        <h2 class="panel-nav__title" data-default-title="<?php echo $this->__('Search')?>">
            <span class="active"><?php echo $this->__('Search')?></span>
        </h2>
        <button type="button" onclick="window.searchBox.onClosePanelClick();" class="panel-nav__action panel-nav__action--right panel-nav__action--cancel not-lap-land js-close-panel">
        </button>
    </header>
    <form class="search-bar" action="<?php echo $catalogSearchHelper->getResultUrl() ?>" method="get">
        <div class="form-search">
            <div class="form-search-container">
                <div class="form-search-el-container">
                    <div class="form-search-input-container">
                        <input type="search" name="<?php echo $catalogSearchHelper->getQueryParamName() ?>" value="<?php echo $catalogSearchHelper->getEscapedQueryText() ?>" class="search-bar__textfield textfield" placeholder="<?php echo $this->__('Search')?>" maxlength="<?php echo $catalogSearchHelper->getMaxQueryLength();?>" />
                        <div class="search-autocomplete-indicator" style="display:none;"></div>
                        <div class="search-autocomplete-close" style="display:none;"></div>
                    </div>
                </div>
            </div>
            <button type="submit" title="<?php echo $this->__('Search') ?>" class="form__submit button continue"><?php echo $this->__('Search') ?></button>
            <div class="search-autocomplete-container" style="display:none;">
                <div class="search-autocomplete-arrow"></div>
                <div class="search-autocomplete"></div>
            </div>
        </div>
    </form>
    <!-- .search-bar -->
    <script type="text/javascript">
        //<![CDATA[
        //Show search input
        window.searchBox = new awMobile2.app.searchBox({
            url: '<?php echo $catalogSearchHelper->getSuggestUrl() ?>'
        });
        //]]>
    </script>
</div>