<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Mobile2
 * @version    2.0.2
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><?php
    $_product = $this->getProduct();
    $_id = $_product->getId();
?>
<?php if ($_product->getCanShowPrice() !== false):?>
    <div class="price-box">
    <?php if (($_min = $this->getMinAmount()) && ($_max = $this->getMaxAmount()) && ($_min == $_max)): ?>
        <span class="price regular-price" id="product-price-<?php echo $_id ?><?php echo $this->getIdSuffix() ?>">
            <?php echo Mage::helper('core')->currency($_min, true, false) ?>
        </span>
    <?php elseif (($_min = $this->getMinAmount()) && $_min != 0): ?>
        <span class="label"><?php echo Mage::helper('enterprise_giftcard')->__('From') ?></span>
        <span class="price regular-price" id="min-product-price-<?php echo $_id ?><?php echo $this->getIdSuffix() ?>">
            <?php echo Mage::helper('core')->currency($_min,true,false) ?>
        </span>
    <?php endif; ?>
    </div>
<?php endif; ?>
