<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Mobile2
 * @version    2.0.2
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><?php
/** @var $this Enterprise_Rma_Block_Return_View */
?>
<?php
    $_rma = $this->getRma();
    $_order = $this->getOrder();
    $additionalData = $this->getAdditionalData();
?>
<div class="rma-view">
    <div class="order__section">
        <h2 class="order__section-title"><?php echo $this->__('Request Information') ?></h2>
        <p><?php echo $this->__('ID') ?>: <?php echo $this->escapeHtml($_rma->getIncrementId()) ?></p>
        <p><?php echo $this->__('Order ID') ?>: <a href="<?php echo $this->getOrderUrl($_rma) ?>"><?php echo $this->escapeHtml($_rma->getOrderIncrementId()) ?></a></p>
        <p><?php echo $this->__('Date Requested') ?>: <?php echo Mage::helper('enterprise_rma')->getFormatedDate($_rma->getDateRequested()) ?></p>
        <p><?php echo $this->__('Email Address') ?>: <?php echo $this->escapeHtml($_order->getCustomerEmail()) ?></p>
        <p><?php echo $this->__('Contact Email Address') ?>: <?php echo $this->escapeHtml($_rma->getCustomerCustomEmail()) ?></p>
    </div>
    <div class="order__section">
        <h2 class="order__section-title"><?php echo $this->__('Shipping Address') ?></h2>
        <address class="order__address">
            <?php echo $this->getAddress() ?>
        </address>
    </div>
    <?php $trackingNumbers = $this->getTrackingNumbers() ?>
    <?php if ($this->isPrintShippingLabelAllowed() || $trackingNumbers->count()): ?>
        <div class="order__section">
            <form method="post" id="rma_track_info" class="form">
                <h2 class="order__section-title">
                    <?php echo $this->__('Shipping and Tracking Information') ?>
                </h2>
                <div>
                    <?php if ($trackingNumbers->count()): ?>
                        <a class="f-left"
                           href="<?php echo $this->helper('enterprise_rma')->getTrackingPopupUrlBySalesModel($this->getRma()) ?>"
                           target="_blank"
                           title="<?php echo $this->__('Track this shipment') ?>">
                            <?php echo $this->__('Track this shipment') ?>
                        </a>
                    <?php endif ?>
                    <?php if ($this->canShowButtons()): ?>
                        <?php //echo $this->getPrintShippingLabelButton() ?>
                        <?php echo $this->getShowPackagesButton() ?>
                    <?php endif; ?>
                </div>
                <div>
                    <table class="data-table" id="track-info-table">
                        <thead>
                        <tr class="data-table-row">
                            <th><span class="nobr"><?php echo $this->__('Carrier') ?></span></th>
                            <th><span class="nobr"><?php echo $this->__('Number') ?></span></th>
                            <th><span class="nobr"><?php echo $this->__('Action') ?></span></th>
                        </tr>
                        </thead>
                        <tbody id="track-info-tbody">
                        <?php echo $this->getTrackingInfo('tracking') ?>
                        </tbody>
                        <?php if ($this->isPrintShippingLabelAllowed()): ?>
                            <tfoot>
                            <tr class="data-table-row">
                                <td>
                                    <select name="tracking_carrier_select" id="tracking_carrier_select" class="form__select required-entry">
                                        <option value = ""></option>
                                        <?php foreach($this->getCarriers() as $key => $value): ?>
                                            <option value="<?php echo $key ?>"><?php echo $this->escapeHtml($value) ?></option>
                                        <?php endforeach ?>
                                    </select>
                                </td>
                                <td>
                                    <input type="text" class="form__textfield textfield required-entry" value="" name="tracking_number_input" id="tracking_number_input">
                                </td>
                                <td>
                                    <button type="button" class="button" onclick="addTrackNumber()" title="<?php echo $this->__('Add') ?>"><span><span><?php echo $this->__('Add') ?></span></span></button>
                                </td>
                            </tr>
                            </tfoot>
                        <?php endif ?>
                    </table>
                </div>
            </form>
            <script type="text/javascript">
                //<![CDATA[
                var trackDataForm = new VarienForm('rma_track_info', false);
                function addTrackNumber() {
                    if (trackDataForm.validator.validate()) {
                        new Ajax.Updater('track-info-tbody', '<?php echo $this->getAddLabelUrl() ?>', {
                            onCreate: function() { $('ajax_loader').show() },
                            onComplete: function() {
                                $('ajax_loader').hide();
                            },
                            method: 'post',
                            parameters : {
                                carrier: $("tracking_carrier_select").value,
                                number: $("tracking_number_input").value
                            }
                        });
                    }
                }
                //]]>
            </script>
        </div>
    <?php endif ?>
    <div class="order__section">
        <h2 class="order__section-title">
            <?php echo $this->__('Items Return Requested For') ?>
        </h2>
        <div>
            <table class="data-table" id="my-returns-items-table">
                <thead>
                <tr class="data-table-row">
                    <th><span class="nobr"><?php echo $this->__('Product Name') ?></span></th>
                    <th><?php echo $this->__('SKU') ?></th>
                    <th><?php echo $this->__('Condition') ?></th>
                    <th><?php echo $this->__('Resolution') ?></th>
                    <th><span class="nobr"><?php echo $this->__('Request Qty') ?></span></th>
                    <th><?php echo $this->__('Qty') ?></th>
                    <th><?php echo $this->__('Status') ?></th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($this->getItems() as $key=>$item): ?>
                    <tr class="data-table-row">
                        <td>
                            <?php echo $this->escapeHtml($item->getProductName()) ?>
                            <div class="product-card__selected-options">
                                <?php if ($_options = $this->getItemOptions($item)):?>
                                    <?php foreach ($_options as $_option) : ?>
                                        <p class="product-option">
                                            <?php echo $this->htmlEscape($_option['label']) ?>: <?php echo $_option['value'] ?>
                                        </p>
                                    <?php endforeach; ?>
                                <?php endif;?>
                            </div>
                        </td>
                        <td><?php echo $this->escapeHtml($item->getProductSku()) ?></span></td>
                        <td><?php echo $this->escapeHtml($this->getAttributeValue($item->getId(), 'condition')) ?></td>
                        <td><?php echo $this->escapeHtml($this->getAttributeValue($item->getId(), 'resolution')) ?></td>
                        <td><?php echo $this->escapeHtml($this->helper('enterprise_rma')->parseQuantity($item->getQtyRequested(), $item)); ?></td>
                        <td><?php echo $this->escapeHtml($this->helper('enterprise_rma')->getQty($item));?></td>
                        <td><span class="nobr"><?php echo $this->escapeHtml($item->getStatusLabel()) ?></span></td>
                        <td>
                            <a id="as_<?php echo $key ?>" href="javascript:void(0)" onclick="showHiddenForm(<?php echo $key ?>)"><?php echo $this->__('Show Details') ?></a>
                            <a id="ah_<?php echo $key ?>" style="display:none" href="javascript:void(0)" onclick="hideHiddenForm(<?php echo $key ?>)"><?php echo $this->__('Hide Details') ?></a>
                        </td>
                    </tr>
                    <tr class="data-table-row" id="shf_<?php echo $key ?>" style="display:none">
                        <td colspan="8" style="background:#F5F5F5;">
                            <div style="display:inline; float:left;width:40%;"><?php echo $this->__('Questions') ?>:</div>
                            <div style="display:inline; float:left;width:40%;"><?php echo $this->__('Answers') ?>:</div>
                            <div style="clear: both;"></div>
                            <?php $i = 0; ?>
                            <?php foreach($this->getRealValueAttributes($item->getId()) as $code=>$attribute): ?>
                                <?php if (!in_array($code, $this->getAttributeFilter()) && !empty($attribute['value']) && $this->getAttributeLabel($item->getId(), $code)): $i++;?>
                                    <div style="display:inline; float:left;width:40%;padding-left:20px"><li><?php echo $this->getAttributeLabel($item->getId(), $code) ?></li></div>
                                    <div style="display:inline; float:left;width:40%;"><li><?php echo $this->getAttributeValue($item->getId(), $code) ?></li></div>
                                    <div style="clear: both;"></div>
                                <?php endif; ?>
                            <?php endforeach; ?>
                        </td>
                    </tr>
                <?php if (!$i): ?>
                    <script type="text/javascript">
                        //<![CDATA[
                        $('shf_'+<?php echo $key?>).remove();
                        $('as_'+<?php echo $key?>).remove();
                        $('ah_'+<?php echo $key?>).remove();
                        //]]>
                    </script>
                <?php endif; ?>
                <?php endforeach; ?>
                </tbody>
            </table>
            <script type="text/javascript">
                //<![CDATA[
                function showHiddenForm(key)
                {
                    $('shf_'+key).show();
                    $('as_'+key).hide();
                    $('ah_'+key).show();
                }
                function hideHiddenForm(key)
                {
                    $('shf_'+key).hide();
                    $('as_'+key).show();
                    $('ah_'+key).hide();
                }
                //]]>
            </script>
        </div>
    </div>
    <div class="order__section">
        <h2 class="order__section-title">
            <?php echo $this->__('Leave Comment') ?>
        </h2>
        <form method="post" class="form" id="rma_comment" action="<?php echo $this->getSubmitUrl() ?>">
            <p class="form__field form__field--required">
                <label for="rma_comment_text" class="form__label form__label--required"><?php echo $this->__('Comment Text') ?></label>
                <textarea name="comment" id="rma_comment_text" class="form__textfield textfield required-entry" cols="5" rows="3"></textarea>
            </p>
            <p class="form__submit-wrapper">
                <button type="submit" class="button" id="submit.save"><?php echo $this->__('Submit Comment')?></button>
            </p>
        </form>
        <script type="text/javascript">
            //<![CDATA[
            var dataForm = new VarienForm('rma_comment', true);
            //]]>
        </script>
    </div>
    <div class="order__section">
        <?php $_comments = $this->getComments(); ?>
        <?php if (!empty($_comments)): ?>
            <?php foreach($_comments as $_comment): ?>
                <?php if ($_comment->getIsVisibleOnFront()): ?>
                    <div class="rma-comment">
                        <strong><?php echo $this->formatDate($_comment->getCreatedAt()) ?> <?php echo $this->formatTime($_comment->getCreatedAt()) ?></strong>
                        <span class="separator">|</span>
                        <strong>
                            <?php if ($_comment->getIsAdmin()): ?>
                                <?php echo $this->__('Customer Service')?>
                            <?php else: ?>
                                <?php echo $this->escapeHtml($this->getCustomerName())?>
                            <?php endif; ?>
                        </strong>
                        <br />
                        <span>
                            <?php echo nl2br($this->escapeHtml($_comment->getComment())); ?>
                        </span>
                    </div>
                <?php endif; ?>
            <?php endforeach; ?>
        <?php endif; ?>
    </div>
</div>