<div class="account-create">
    <?php echo $this->getChildHtml('form_fields_before')?>
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <form action="<?php echo $this->getPostActionUrl() ?>" method="post" id="form-validate">
        <div class="fieldset">
            <input type="hidden" name="success_url" value="<?php echo $this->getSuccessUrl() ?>" />
            <input type="hidden" name="error_url" value="<?php echo $this->getErrorUrl() ?>" />
            <h2 class="legend"><?php echo $this->__('Personal Information') ?></h2>            
            <!-- 短信验证.form__field -->
            <div class="fieldset">
                <ul class="form-list">
                    <li class="fields">       
                        <div class="input-box">     
                        <fieldset id="amcustomerattr19" class="amcustomerattr">
                        <input placeholder="Mobile Number*" id="default_mobile_number" name="amcustomerattr[default_mobile_number]" value="" class=" required-entry input-text required-entry" type="text">
                        </fieldset>
                    </li>
                    <li class="fields">
                        <div class="field">
                            <div class="input-box">
                                <input placeholder="Validation Code*" type="Validation_Code" name="Validation_Code" id="Validation_Code" title="Validation_Code" class="input-text required-entry validate-number" />
                            </div>
                      <input type="button"  id="btnValidation" value="Get Validation Code" class="form_validation button">
                        </div>
                        </div>
                    </li>
                </ul>
            </div>
            <!-- end 短信验证.form__field-->
            <ul class="form-list">
                <li class="wide">
                    <div class="input-box">
                        <input placeholder="<?php echo $this->__('Email Address') ?>*" type="text" name="email" id="email_address" value="<?php echo $this->escapeHtml($this->getFormData()->getEmail()) ?>" title="<?php echo $this->__('Email Address') ?>" class="input-text validate-email required-entry" />
                    </div>
                </li>
                <li class="fields">
                    <?php echo $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getFormData())->setForceUseCustomerAttributes(true)->toHtml() ?>
                </li>
            <?php $_dob = $this->getLayout()->createBlock('customer/widget_dob') ?>
            <?php if ($_dob->isEnabled()): ?>
                <li><?php echo $_dob->setDate($this->getFormData()->getDob())->toHtml() ?></li>
            <?php endif ?>
            <?php $_taxvat = $this->getLayout()->createBlock('customer/widget_taxvat') ?>
            <?php if ($_taxvat->isEnabled()): ?>
                <li><?php echo $_taxvat->setTaxvat($this->getFormData()->getTaxvat())->toHtml() ?></li>
            <?php endif ?>
            <?php $_gender = $this->getLayout()->createBlock('customer/widget_gender') ?>
            <?php if ($_gender->isEnabled()): ?>
                <li><?php echo $_gender->setGender($this->getFormData()->getGender())->toHtml() ?></li>
            <?php endif ?>
            </ul>
        </div>
    <?php if($this->getShowAddressFields()): ?>
        <div class="fieldset">
            <input type="hidden" name="create_address" value="1" />
            <h2 class="legend"><?php echo $this->__('Address Information') ?></h2>
            <ul class="form-list">
                <li class="fields">
                    <div class="field">
                        <label for="company"><?php echo $this->__('Company') ?></label>
                        <div class="input-box">
                            <input type="text" name="company" id="company" value="<?php echo $this->escapeHtml($this->getFormData()->getCompany()) ?>" title="<?php echo $this->__('Company') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('company') ?>" />
                        </div>
                    </div>
                    <div class="field">
                        <label for="telephone" class="required"><em>*</em><?php echo $this->__('Telephone') ?></label>
                        <div class="input-box">
                            <input type="text" name="telephone" id="telephone" value="<?php echo $this->escapeHtml($this->getFormData()->getTelephone()) ?>" title="<?php echo $this->__('Telephone') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('telephone') ?>" />
                        </div>
                    </div>
                </li>
            <?php $_streetValidationClass = $this->helper('customer/address')->getAttributeValidationClass('street'); ?>
                <li class="wide">
                    <label for="street_1" class="required"><em>*</em><?php echo $this->__('Street Address') ?></label>
                    <div class="input-box">
                        <input type="text" name="street[]" value="<?php echo $this->escapeHtml($this->getFormData()->getStreet(1)) ?>" title="<?php echo $this->__('Street Address') ?> 1" id="street_1" class="input-text <?php echo $_streetValidationClass ?>" />
                    </div>
                </li>
            <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
            <?php for ($_i = 2, $_n = $this->helper('customer/address')->getStreetLines(); $_i <= $_n; $_i++): ?>
                <li class="wide">
                    <label for="street_<?php echo $_i; ?>"><?php echo $this->__('Street Address %s', $_i) ?></label>
                    <div class="input-box">
                        <input type="text" name="street[]" value="<?php echo $this->escapeHtml($this->getFormData()->getStreet($_i)) ?>" title="<?php echo $this->__('Street Address %s', $_i) ?>" id="street_<?php echo $_i ?>" class="input-text <?php echo $_streetValidationClass ?>" />
                    </div>
                </li>
            <?php endfor; ?>
                <li class="fields">
                    <div class="field">
                        <label for="city" class="required"><em>*</em><?php echo $this->__('City') ?></label>
                        <div class="input-box">
                            <input type="text" name="city" value="<?php echo $this->escapeHtml($this->getFormData()->getCity()) ?>" title="<?php echo $this->__('City') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('city') ?>" id="city" />
                        </div>
                    </div>
                    <div class="field">
                        <label for="region_id" class="required"><em>*</em><?php echo $this->__('State/Province') ?></label>
                        <div class="input-box">
                            <select id="region_id" name="region_id" title="<?php echo $this->__('State/Province') ?>" class="validate-select" style="display:none;">
                                <option value=""><?php echo $this->__('Please select region, state or province') ?></option>
                            </select>
                            <script type="text/javascript">
                            //<![CDATA[
                                $('region_id').setAttribute('defaultValue', "<?php echo $this->getFormData()->getRegionId() ?>");
                            //]]>
                            </script>
                            <input type="text" id="region" name="region" value="<?php echo $this->escapeHtml($this->getRegion()) ?>" title="<?php echo $this->__('State/Province') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('region') ?>" style="display:none;" />
                        </div>
                    </div>
                </li>
                <li class="fields">
                    <div class="field">
                        <label for="zip" class="required"><em>*</em><?php echo $this->__('Zip/Postal Code') ?></label>
                        <div class="input-box">
                            <input type="text" name="postcode" value="<?php echo $this->escapeHtml($this->getFormData()->getPostcode()) ?>" title="<?php echo $this->__('Zip/Postal Code') ?>" id="zip" class="input-text validate-zip-international <?php echo $this->helper('customer/address')->getAttributeValidationClass('postcode') ?>" />
                        </div>
                    </div>
                    <div class="field">
                        <div class="input-box">
                            <label for="country" class="required"><i class="icon-country"></i><?php echo $this->__('Country') ?><em>*</em></label>
                            <?php echo $this->getCountryHtmlSelect() ?>
                        </div>
                    </div>
                </li>
            </ul>
            <input type="hidden" name="default_billing" value="1" />
            <input type="hidden" name="default_shipping" value="1" />
        </div>
    <?php endif; ?>
        <div class="fieldset">
            <ul class="form-list">
                <li class="fields">
                    <div class="field">
                        <div class="input-box">
                            <input placeholder="<?php echo $this->__('Password') ?>*" type="password" name="password" id="password" title="<?php echo $this->__('Password') ?>" class="input-text required-entry validate-password" />
                        </div>
                    </div>
                    <div class="field">
                        <div class="input-box">
                            <input placeholder="<?php echo $this->__('Confirm Password') ?>*" type="password" name="confirmation" title="<?php echo $this->__('Confirm Password') ?>" id="confirmation" class="input-text required-entry validate-cpassword" />
                        </div>
                    </div>
                </li>                                
            </ul>
        </div>
        <div class="buttons-set">
            <p class="back-link"><a href="#" onclick="history.back();return false;" class="back-link"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
            <button type="submit" id="btnSubmit" title="<?php echo $this->__('Submit') ?>" class="button"><span><span><?php echo $this->__('Submit') ?></span></span></button>
        </div>
        <?php if (Mage::helper('checkout')->isContextCheckout()): ?>
            <input name="context" type="hidden" value="checkout" />
        <?php endif; ?>
    </form>
    <script type="text/javascript">
    //<![CDATA[
        var dataForm = new VarienForm('form-validate', true);
        <?php if($this->getShowAddressFields()): ?>
        new RegionUpdater('country', 'region', 'region_id', <?php echo $this->helper('directory')->getRegionJson() ?>, undefined, 'zip');
        <?php endif; ?>
    //]]>
    </script>
    
<script type="text/javascript">
		//生成随机数验证码
		rnd.today=new Date();
		rnd.seed=rnd.today.getTime();
		function rnd() {
		　　　　rnd.seed = (rnd.seed*9301+49297) % 233280;
		　　　　return rnd.seed/(233280.0);
		};
		function rand(number) {
		　　　　return Math.ceil(rnd()*number);
		};
		// end central randomizer. -->
		
		var wait=30;  
		var rnum=8888;
		function time(o) {  
				if (wait == 0 ) {  
					o.removeAttribute("disabled");            
					o.value="Get A Free Validation Code";
					wait = 30;  				       
				}else{   
					if(wait == 30){
						//此处加ajax发短信，http://sendsms?mobile num=11212&content=aaa+'rynm'
						rnum = rand(8999)+1000;
					    // sendsms(smsurl,rnum);
					}
					wait--;  
					setTimeout(function() {  
						time(o)  
					},  1000)  
					o.setAttribute("disabled", true);
					//调试期，直接显示验证码 
					o.value="["+rnum+"]Wait ...(" + wait + "s)"; 
				}  
			}  
			
		document.getElementById("btnValidation").onclick=function(){time(this);}  
		document.getElementById("btnSubmit").onclick=function(){checkcode();} 

	       //发送短信请求
//		var smsurl = defines.baseSite + '/sendsms.php';
		var smsurl = '/sendsms.php';
		function sendsms(smsurl,smscode){ 
		   new Ajax.Request(smsurl, {
			method: 'GET',
			crossSite: true,
			parameters: 'mobile='+document.getElementById('default_mobile_number').value+'&content=您好，您的短信验证码是：'+smscode+'【美联软通】',
                        contentType: 'application/x-www-form-urlencoded',
			onSuccess: function(text) {  
			    // yourtext = text.responseText.evalJSON(true);  
			    //process something  
			},  
			onFailure: function() {  
			    return false;  
			},  
			onException: function() {  
			    return false;  
			}  
		    });  
		  
		    return true;
		} 

		//验证码检测
		function checkcode(){
		   var smscode = document.getElementById('Validation_Code').value;
		   if(rnum !=smscode){
			document.getElementById('Validation_Code').value="Wrong Code";
		   }
		}
</script> 
<script type="text/javascript">
	document.getElementById("gender")[1].selected=true;
</script>
</div>
