<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Mobile2
 * @version    2.0.2
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><?php if (!($_shippingRateGroups = $this->getShippingRates())): ?>
    <p><?php echo $this->__('Sorry, no quotes are available for this order at this time.') ?></p>
<?php else: ?>
    <?php $_sole = count($_shippingRateGroups) == 1; foreach ($_shippingRateGroups as $code => $_rates): ?>
        <div class="shipping-methods__service">
            <h3 class="shipping-methods__service-name"><?php echo $this->getCarrierName($code) ?></h3>
            <ul class="shipping-methods__methods">
                <?php $_sole = $_sole && count($_rates) == 1; foreach ($_rates as $_rate): ?>
                    <li class="shipping-methods__method">
                        <ul class="form__checkboxes">
                            <?php if ($_rate->getErrorMessage()): ?>
                                <li class="form__radio-label">
                                    <ul class="messages"><li class="error-msg"><ul><li><?php echo $_rate->getErrorMessage() ?></li></ul></li></ul>
                                    <label class="shipping-methods__radio-label">
                                        <?php echo $_rate->getMethodTitle() ?>
                                    </label>
                                </li>
                            <?php else: ?>
                                <li class="form__radio-label">
                                    <input type="radio" name="shipping_method" class="form__radio" value="<?php echo $_rate->getCode() ?>" id="s_method_<?php echo $_rate->getCode() ?>"<?php if($_rate->getCode()===$this->getAddressShippingMethod()) echo ' checked="checked"' ?>>
                                    <label class="shipping-methods__radio-label" for="s_method_<?php echo $_rate->getCode() ?>">
                                        <?php echo $_rate->getMethodTitle() ?>
                                        <strong class="shipping-methods__price">
                                            <?php $_excl = $this->getShippingPrice($_rate->getPrice(), $this->helper('tax')->displayShippingPriceIncludingTax()); ?>
                                            <?php $_incl = $this->getShippingPrice($_rate->getPrice(), true); ?>
                                            <?php echo $_excl; ?>
                                            <?php if ($this->helper('tax')->displayShippingBothPrices() && $_incl != $_excl): ?>
                                                (<?php echo $this->__('Incl. Tax'); ?> <?php echo $_incl; ?>)
                                            <?php endif; ?>
                                        </strong>
                                    </label>
                                    </li>
                            <?php endif ?>
                        </ul>
                    </li>
                <?php endforeach; ?>
            </ul>
        </div><!-- .shipping-methods__service -->
    <?php endforeach; ?>
<?php endif; ?>
<?php if (($_shippingRateGroups = $this->getShippingRates())): ?>
<script type="text/javascript">
    //<![CDATA[
    window.shippingLabels = [];
    <?php foreach ($_shippingRateGroups as $code => $_rates): ?>
        <?php foreach ($_rates as $_rate): ?>
            window.shippingLabels.<?php echo $_rate->getCode() ?> = "<?php echo $this->getCarrierName($code) ?>";
        <?php endforeach; ?>
    <?php endforeach; ?>
    //]]>
</script>
<?php endif; ?>