<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Mobile2
 * @version    2.0.2
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><div class="nav__list customer-account-login">
    <form action="<?php echo $this->helper('aw_mobile2/url')->getCustomerPostActionUrl() ?>" method="post" id="user_login_form" class="nav__list-inner">
        <?php echo $this->getMessagesBlock()->addMessages(Mage::getSingleton('customer/session')->getMessages(true))->getGroupedHtml() ?>
        <?php echo $this->getBlockHtml('formkey'); ?>
        <p class="form__field form__field--required">
            <!--<label for="email" class="form__label form__label--required"><?php echo $this->__('Email Address') ?></label>-->
            <input type="email" placeholder="Email or Member ID" class="form__textfield textfield validate-email required-entry" name="login[username]" id="email" value="<?php echo $this->htmlEscape($this->getUsername()) ?>" title="<?php echo $this->__('Email Address') ?>">
        </p><!-- .form__field -->
        <p class="form__field form__field--required">
            <!--<label for="pass" class="form__label form__label--required"><?php echo $this->__('Password') ?></label>-->
            <input placeholder="Password" class="form__textfield textfield required-entry validate-password" type="password" name="login[password]" id="pass" title="<?php echo $this->__('Password') ?>" />
        </p><!-- .form__field -->
        <?php echo $this->getChildHtml('form.additional.info'); ?>
        <p class="form__submit-wrapper">
        	<a id="forgot_pass_link" href="javascript:void(0);"><?php echo $this->__('Forgot Password?') ?></a>
            <button type="submit" title="<?php echo $this->__('Login') ?>" class="form__submit button continue" style="background-color:#F4A137;" onclick="window.customerAccount.login()"><?php echo $this->__('Login') ?></button>
            <!--<button id="create_form_link" type="button" title="<?php echo $this->__('Create an Account') ?>" class="form__submit button continue-another" style="border:1px solid #F4A137; color:#F4A137;" onclick=""><?php echo $this->__('Create an Account') ?></button>-->
        </p><!-- .form__submit-wrapper -->
    </form>
    <script type="text/javascript">
        //<![CDATA[
        if (typeof window.customerAccount != 'undefined') {
            window.customerAccount.setLoginForm('user_login_form');
            window.customerAccount.setForgotLink('forgot_pass_link');
            window.customerAccount.setRegisterLink('create_form_link');
        }
        //]]>
    </script>
    <div class="nav__list-shadow"></div>
</div>
