<div class="nav__list nav__list--subcategory customer-account-register">
    <div class="nav__list-inner customer-account-register-container">
        <div class="customer-form-register-before">
            <?php echo $this->getChildHtml('form_fields_before')?>
        </div>
        <form action="<?php echo $this->helper('aw_mobile2/url')->getRegisterPostUrl() ?>" method="post" id="user_create_form" class="form">
            <input type="hidden" name="success_url" value="<?php echo $this->getSuccessUrl() ?>" />
            <input type="hidden" name="error_url" value="<?php echo $this->getErrorUrl() ?>" />
			<p class="form__field form__field--required">
		<!--<label class="form__label form__label--required">Mobile Number</label>-->
		<input type="text" placeholder="Mobile Number" class="form__textfield textfield required-entry validate-number validation-failed" name="amcustomerattr[default_mobile_number]" id="default_mobile_number" value="" title="Mobile Number">
		</p><!-- .form__field -->
		
			<p class="form__field form__field--required">
		<!--<label class="form__label form__label--required">Validation Code</label>-->
		<input type="text" placeholder="Validation Code" class="form__textfield textfield validation-code required-entry validate-number validation-failed" name="Validation_Code" id="Validation_Code" value="" title="Validation Code">
		<input type="button" id="btnValidation" value="Get Validation Code" class="form_validation" />  
		</p>		
			<!-- .form__field -->
		
				<p class="form__field form__field--required">
                <!--<label for="email_address" class="form__label form__label--required"><?php echo $this->__('Email Address') ?></label>-->
                <input type="email" placeholder="Email" class="form__textfield textfield validate-email required-entry" name="email" id="email_address" value="<?php echo $this->htmlEscape($this->getFormData()->getEmail()) ?>" title="<?php echo $this->__('Email Address') ?>">
            </p><!-- .form__field -->
            <?php echo $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getFormData())->toHtml() ?>
            <?php $_dob = $this->getLayout()->createBlock('customer/widget_dob')->setClassName('register_customer_dob') ?>
            <?php if ($_dob->isEnabled()): ?>
                <?php echo $_dob->setDate($this->getFormData()->getDob())->toHtml() ?>
            <?php endif ?>
            <?php $_taxvat = $this->getLayout()->createBlock('customer/widget_taxvat') ?>
            <?php if ($_taxvat->isEnabled()): ?>
                <?php echo $_taxvat->setTaxvat($this->getFormData()->getTaxvat())->toHtml() ?>
            <?php endif ?>
            <?php $_gender = $this->getLayout()->createBlock('customer/widget_gender') ?>
            <?php if ($_gender->isEnabled()): ?>
                <?php echo $_gender->setGender($this->getFormData()->getGender())->toHtml() 				
				?>
					<script type="text/javascript">
						document.getElementById("gender")[1].selected=true;
					</script>
            <?php endif ?>
            <?php $customerAttributes = $this->getChild('customer_form_user_attributes');?>
            <?php if ($customerAttributes && $customerAttributes instanceof Enterprise_Customer_Block_Form): ?>
                <?php $customerAttributes->setShowContainer(false);?>
                <?php $this->restoreSessionData($customerAttributes->getForm());?>
                <?php echo $customerAttributes->toHtml()?>
            <?php endif;?>
            <?php if($this->getShowAddressFields()): ?>
                <p class="form__field">
                    <label class="form__label" for="company"><?php echo $this->__('Company') ?></label>
                    <input type="text" class="form__textfield textfield" id="company" name="company" value="<?php echo $this->htmlEscape($this->getFormData()->getCompany()) ?>" title="<?php echo $this->__('Company') ?>">
                </p><!-- .form__field -->
                <p class="form__field form__field--required">
                    <label for="telephone" class="form__label form__label--required"><?php echo $this->__('Telephone') ?></label>
                    <input type="tel" class="form__textfield textfield required-entry" name="telephone" value="<?php echo $this->htmlEscape($this->getFormData()->getTelephone()) ?>" title="<?php echo $this->__('Telephone') ?>" id="telephone" />
                </p><!-- .form__field -->

                <p class="form__field form__field--required">
                    <label for="street_1" class="form__label form__label--required"><?php echo $this->__('Address') ?></label>
                    <input type="text" class="form__textfield textfield required-entry" name="street[]" title="<?php echo $this->__('Street Address') ?>" id="street_1" value="<?php echo $this->htmlEscape($this->getFormData()->getStreet(1)) ?>">
                </p><!-- .form__field -->
                <?php for ($_i=2, $_n=$this->helper('customer/address')->getStreetLines(); $_i<=$_n; $_i++): ?>
                    <p class="form__field">
                        <input type="text" class="form__textfield textfield" title="<?php echo $this->__('Street Address %s', $_i) ?>" name="street[]" id="street_<?php echo $_i?>" value="<?php echo $this->htmlEscape($this->getFormData()->getStreet($_i)) ?>">
                    </p><!-- .form__field -->
                <?php endfor ?>
                <p class="form__field form__field--required">
                    <label class="form__label form__label--required" for="city"><?php echo $this->__('City') ?></label>
                    <input type="text" class="form__textfield textfield required-entry" title="<?php echo $this->__('City') ?>" id="city" name="city" value="<?php echo $this->htmlEscape($this->getFormData()->getCity()) ?>">
                </p><!-- .form__field -->
                <p class="form__field form__field--required">
                    <label class="form__label form__label--required" for="region_id"><?php echo $this->__('State/Province') ?></label>
                    <select class="form__select validate-select" id="region_id" name="region_id" title="<?php echo $this->__('State/Province') ?>" style="display:none;">
                        <option value=""><?php echo $this->__('Please select region, state or province') ?></option>
                    </select>
                    <script type="text/javascript">
                        //<![CDATA[
                        $('region_id').setAttribute('defaultValue', "<?php echo $this->getFormData()->getRegionId() ?>");
                        //]]>
                    </script>
                    <input type="text" id="region" name="region" value="<?php echo $this->htmlEscape($this->getRegion()) ?>" title="<?php echo $this->__('State/Province') ?>" class="input-text" style="display:none;" />
                </p><!-- .form__field -->
                <p class="form__field form__field--required">
                    <label for="zip" class="form__label form__label--required"><?php echo $this->__('Zip/Postal Code') ?></label>
                    <input type="text" class="form__textfield textfield validate-zip-international required-entry" title="<?php echo $this->__('Zip/Postal Code') ?>" name="postcode" id="zip" value="<?php echo $this->htmlEscape($this->getFormData()->getPostcode()) ?>" />
                </p><!-- .form__field -->
                <p class="form__field form__field--required">
                    <label class="form__label form__label--required" for="country"><?php echo $this->__('Country') ?></label>
                    <?php echo $this->getCountryHtmlSelect() ?>
                </p><!-- .form__field -->
                <?php $addressAttributes = $this->getChild('customer_form_address_user_attributes');?>
                <?php if ($addressAttributes && $addressAttributes instanceof Enterprise_Customer_Block_Form): ?>
                    <?php $addressAttributes->setEntity($this->getAddress());?>
                    <?php $addressAttributes->setFieldIdFormat('address:%1$s')->setFieldNameFormat('address[%1$s]');?>
                    <?php $this->restoreSessionData($addressAttributes->getForm(), 'address');?>
                    <?php echo $addressAttributes->setShowContainer(false)->toHtml()?>
                <?php endif;?>
                <input type="hidden" name="default_billing" value="1" />
                <input type="hidden" name="default_shipping" value="1" />
            <?php endif ?>
            <div id="register-customer-password">
                <p class="form__field form__field--required">
                    <!--<label for="password" class="form__label form__label--required"><?php echo $this->__('Password') ?></label>-->
                    <input placeholder="Password (6 characters contain numbers and letters)" class="form__textfield textfield required-entry validate-password" type="password" name="password" id="password" title="<?php echo $this->__('Password') ?>" />
                </p><!-- .form__field -->
                <p class="form__field form__field--required">
                    <!--<label for="confirmation" class="form__label form__label--required"><?php echo $this->__('Confirm Password') ?></label>-->
                    <input placeholder="Confirm Password" class="form__textfield textfield required-entry validate-cpassword" type="password" name="confirmation" title="<?php echo $this->__('Confirm Password') ?>" id="confirmation" />
                </p><!-- .form__field -->
            </div>
            <?php if ($this->isNewsletterEnabled()): ?>
                <div class="form__field">
                    <ul class="form__checkboxes">
                        <li class="form__checkboxes-item">
                            <input type="checkbox" class="form__checkbox" name="is_subscribed" id="is_subscribed"<?php if($this->getFormData()->getIsSubscribed()): ?> checked="checked"<?php endif; ?> value="1" title="<?php echo $this->__('Sign Up for Newsletter') ?>">
                            <label for="is_subscribed" class="form__checkbox-label"><?php echo $this->__('Sign Up for Newsletter') ?></label>
                        </li>
                    </ul>
                </div>
            <?php endif ?>
            <?php //echo $this->getChildHtml('persistent.remember.me'); ?>
            <p class="form__submit-wrapper">
                <button type="submit" title="<?php echo $this->__('Register') ?>" class="form__submit button continue" style="background-color:#F4A137" onclick="checkcode();window.customerAccount.register()"><?php echo $this->__('Register') ?></button>
            </p><!-- .form__submit-wrapper -->
            <?php if (Mage::helper('checkout')->isContextCheckout()): ?>
                <input name="context" type="hidden" value="checkout" />
            <?php endif; ?>
        </form>
        <script type="text/javascript">
            //<![CDATA[
            Event.observe(window, 'load', function(e){
                window.customerAccount.setRegisterForm('user_create_form');				
                window.customerAccount.setRegisterTitle(<?php echo Zend_Json::encode($this->__('Register'));?>);
            });
            //]]>
        </script>

	<script type="text/javascript">
		//生成随机数验证码
		rnd.today=new Date();
		rnd.seed=rnd.today.getTime();
		function rnd() {
		　　　　rnd.seed = (rnd.seed*9301+49297) % 233280;
		　　　　return rnd.seed/(233280.0);
		};
		function rand(number) {
		　　　　return Math.ceil(rnd()*number);
		};
		// end central randomizer. -->
		
		var wait=10;  
		var rnum=8888;
		function time(o) {  
				if (wait == 0 ) {  
					o.removeAttribute("disabled");            
					o.value="Get A Free Validation Code";
					wait = 10;  				       
				}else{  
					o.setAttribute("disabled", true); 
					o.value="Wait for ...(" + wait + ")";  
					if(wait == 10){
						//此处加ajax发短信，http://sendsms?mobile num=11212&content=aaa+'rynm'
						rnum = rand(8999)+1000;
					        sendsms(smsurl,rnum);
					}
					wait--;  
					setTimeout(function() {  
						time(o)  
					},  1000)  
				}  
			}  
			
		document.getElementById("btnValidation").onclick=function(){time(this);}  

	       //发送短信请求
		var smsurl = 'http://skymazon.sunpop.cn/sendsms.php';
		function sendsms(smsurl,smscode){ 
		   new Ajax.Request(smsurl, {
			method: 'GET',
			crossSite: true,
			parameters: 'mobile='+document.getElementById('default_mobile_number').value+'&content=您好，您的短信验证码是：'+smscode+'【美联软通】',
                        contentType: 'application/x-www-form-urlencoded',
			onSuccess: function(text) {  
			    // yourtext = text.responseText.evalJSON(true);  
			    //process something  
			},  
			onFailure: function() {  
			    return false;  
			},  
			onException: function() {  
			    return false;  
			}  
		    });  
		  
		    return true;
		} 

		//验证码检测
		function checkcode(){
		   var smscode = document.getElementById('Validation_Code').value;
		   if(rnum !=smscode){
			document.getElementById('Validation_Code').value="Sorry ,you get a wrong Validation Code";
		   }
		}
	</script> 
    </div>
</div>