<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Mobile2
 * @version    2.0.2
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><?php //TODO create test account and test?>
<div class="moneybookers-payment">
    <table>
        <tr>
            <td>
                <iframe src="<?php echo Mage::getUrl('moneybookers/processing/placeform') ?>"></iframe>
            </td>
        </tr>
        <tr>
            <td style="text-align:center;">
                <img src="<?php echo $this->getMoneybookersLogoSrc() ?>" title="Powered by Moneybookers" alt="Powered by Moneybookers" />
            </td>
        </tr>
    </table>
</div>