<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Mobile2
 * @version    2.0.2
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><?php
    $oneMethod = sizeof($this->getMethods()) <= 1;
?>
<ul class="form__radios" id="checkout-payment-method-load">
    <?php foreach ($this->getMethods() as $_method): $_code = $_method->getCode() ?>
        <li class="form__radios-item">
            <?php if( !$oneMethod ): ?>
                <input type="radio" id="p_method_<?php echo $_code ?>" value="<?php echo $_code ?>" class="form__radio" name="payment[method]" title="<?php echo $this->htmlEscape($_method->getTitle()) ?>" onclick="payment.switchMethod('<?php echo $_code ?>')"<?php if($this->getSelectedMethodCode()==$_code): ?> checked="checked"<?php endif; ?>>
                <label class="form__radio-label" for="p_method_<?php echo $_code ?>" value="<?php echo $_code ?>">
                    <?php echo $this->getMethodTitle($_method) ?> <?php echo $this->getMethodLabelAfterHtml($_method) ?>
                </label>
            <?php else: ?>
                <input type="radio" id="p_method_<?php echo $_code ?>" value="<?php echo $_code ?>" class="form__radio no-display" name="payment[method]" title="<?php echo $this->htmlEscape($_method->getTitle()) ?>" checked="checked">
                <label for="p_method_<?php echo $_code ?>" class="form__radio-label">
                    <?php echo $this->getMethodTitle($_method) ?> <?php echo $this->getMethodLabelAfterHtml($_method) ?>
                </label>
                <?php $oneMethod = $_code; ?>
            <?php endif; ?>
            <?php if ($html = $this->getPaymentMethodFormHtml($_method)): ?>
                <ul>
                    <li>
                        <?php echo $html; ?>
                    </li>
                </ul>
            <?php endif; ?>
        </li>
    <?php endforeach; ?>
</ul>
<?php echo $this->getChildChildHtml('additional'); ?>
<script type="text/javascript">
    //<![CDATA[
    <?php echo $this->getChildChildHtml('scripts'); ?>
    payment.init();
    <?php if (is_string($oneMethod)): ?>
    payment.switchMethod('<?php echo $oneMethod ?>');
    <?php endif; ?>
    window.paymentLabels = [];
    <?php foreach ($this->getMethods() as $_method): $_code = $_method->getCode() ?>
        window.paymentLabels.<?php echo $_code ?> = "<?php echo $this->htmlEscape($_method->getTitle()) ?>";
    <?php endforeach; ?>
    //]]>
</script>