<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Mobile2
 * @version    2.0.2
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><div class="checkout-onepage-payment-additional-giftcardaccount">
<p class="note">
    <?php $_url = Mage::getUrl('checkout/cart'); ?>
    <?php echo Mage::helper('enterprise_giftcardaccount')->__('To add or remove gift cards, <a href="%s">click here</a>.', $_url); ?><br />

    <?php if ((float)$this->getAppliedGiftCardAmount()): ?>
        <?php $amount = Mage::helper('core')->currency($this->getAppliedGiftCardAmount(), true); ?>
        <?php echo Mage::helper('enterprise_giftcardaccount')->__('Gift Card amount applied to order: %s', $amount); ?>
    <?php endif; ?>
</p>
</div>
