<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Mobile2
 * @version    2.0.2
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?>quoteBaseGrandTotal = <?php echo (float)$this->_getQuote()->getBaseGrandTotal(); ?>;
var isGiftCardApplied = <?php if($this->isFullyPaidAfterApplication()): ?>true<?php else: ?>false<?php endif; ?>;
var epsilon = 0.0001;
function enablePaymentMethods(free) {
    Payment.prototype.init = function () {
        var elements = Form.getElements(this.form);
        var methodName = '';
        for (var i=0; i < elements.length; i++) {
            if (elements[i].name == 'payment[method]'
                || elements[i].name == 'payment[use_customer_balance]'
                || elements[i].name == 'payment[use_reward_points]'
            ) {
                methodName = elements[i].value;
                if ((free && methodName == 'free') || (!free && methodName != 'free')) {
                    $((elements[i]).parentNode).show();
                    if ($('p_method_' + (methodName)) && $('p_method_' + (methodName)).checked) {
                        payment.switchMethod(methodName);
                    }
                    if (free) {
                        elements[i].checked = true;
                        this.switchMethod('free');
                    }
                } else {
                    $((elements[i]).parentNode).hide();
                }
            } else {
                if ($('p_method_' + methodName) && $('p_method_' + methodName).checked) {
                    elements[i].disabled = false;
                } else {
                    elements[i].disabled = true;
                }
            }
        }
    };
}
if (quoteBaseGrandTotal < epsilon && isGiftCardApplied) {
    enablePaymentMethods(true);
} else if (quoteBaseGrandTotal >= epsilon) {
    enablePaymentMethods(false);
}
