<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Mobile2
 * @version    2.0.2
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><div class="account-info">
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <form action="<?php echo $this->getUrl('customer/account/editPost') ?>" method="post" class="form" id="form-validate">
        <p class="required">
            <?php echo $this->__('Required Fields') ?>
        </p>
        <?php echo $this->getBlockHtml('formkey')?>
        <?php echo $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getCustomer())->toHtml() ?>
        <p class="form__field form__field--required">
            <label class="form__label form__label--required"><?php echo $this->__('Email Address') ?></label>
            <input type="email" name="email" id="email" value="<?php echo $this->htmlEscape($this->getCustomer()->getEmail()) ?>" title="<?php echo $this->__('Email Address') ?>" class="form__textfield textfield required-entry validate-email">
        </p><!-- .form__field -->
        <?php $_dob = $this->getLayout()->createBlock('customer/widget_dob')->setClassName('edit_customer_dob') ?>
        <?php if ($_dob->isEnabled()): ?>
            <?php echo $_dob->setDate($this->getCustomer()->getDob())->toHtml() ?>
        <?php endif ?>
        <?php $_taxvat = $this->getLayout()->createBlock('customer/widget_taxvat') ?>
        <?php if ($_taxvat->isEnabled()): ?>
            <?php echo $_taxvat->setTaxvat($this->getCustomer()->getTaxvat())->toHtml() ?>
        <?php endif ?>
        <?php $_gender = $this->getLayout()->createBlock('customer/widget_gender') ?>
        <?php if ($_gender->isEnabled()): ?>
            <?php echo $_gender->setGender($this->getCustomer()->getGender())->toHtml() ?>
        <?php endif ?>

        <?php $userDefinedAttributes = $this->getLayout()->getBlock('customer_form_user_attributes'); ?>
        <?php if ($userDefinedAttributes && $userDefinedAttributes instanceof Enterprise_Customer_Block_Form):?>
            <?php echo $userDefinedAttributes->setEntity($this->getCustomer())->toHtml(); ?>
        <?php endif;?>

        <div class="form__field">
            <ul class="form__checkboxes">
                <li class="form__checkboxes-item">
                    <input type="checkbox" id="change_password"  name="change_password" <?php if($this->getCustomer()->getChangePassword()==1): ?> checked="checked"<?php endif; ?> class="form__checkbox">
                    <label for="change_password" id="change_password_label" class="form__checkbox-label">
                        <?php echo $this->__('Change Password') ?>
                    </label>
                </li>
            </ul>
        </div><!-- .form__field -->

        <div style="display:none;">
            <p class="form__field form__field--required">
                <label class="form__label form__label--required"><?php echo $this->__('Current Password') ?></label>
                <input type="password" title="<?php echo $this->__('Current Password') ?>" name="current_password" id="current_password" class="form__textfield textfield">
            </p><!-- .form__field -->

            <p class="form__field form__field--required">
                <label class="form__label form__label--required"><?php echo $this->__('New Password') ?></label>
                <input type="password" title="<?php echo $this->__('New Password') ?>" name="password" id="password" class="form__textfield textfield validate-password">
            </p><!-- .form__field -->

            <p class="form__field form__field--required">
                <label class="form__label form__label--required"><?php echo $this->__('Confirm New Password') ?></label>
                <input type="password" title="<?php echo $this->__('Confirm New Password') ?>" name="confirmation" id="confirmation" class="form__textfield textfield validate-cpassword">
            </p><!-- .form__field -->
        </div>
        <p class="form__submit-wrapper">
            <button type="submit" title="<?php echo $this->__('Save') ?>" class="form__submit button continue-another"><?php echo $this->__('Save') ?></button>
        </p><!-- .form__submit-wrapper -->
    </form>
</div>
<script type="text/javascript">
    //<![CDATA[
    var dataForm = new VarienForm('form-validate', true);
    function setPasswordForm(arg){
        if(arg){
            $('current_password').up(1).show();
            $('current_password').addClassName('required-entry');
            $('password').addClassName('required-entry');
            $('confirmation').addClassName('required-entry');

        }else{
            $('current_password').up(1).hide();
            $('current_password').removeClassName('required-entry');
            $('password').removeClassName('required-entry');
            $('confirmation').removeClassName('required-entry');
        }
    }
    $('change_password').observe('change', function(e){
        setPasswordForm($('change_password').checked);
    });
    <?php if($this->getCustomer()->getChangePassword()): ?>
    setPasswordForm(true);
    <?php endif; ?>
    //]]>
</script>