<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Mobile2
 * @version    2.0.2
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><div class="nav__list nav__list--subcategory customer-account-forgotpassword">
    <form action="<?php echo $this->helper('aw_mobile2/url')->getForgotPostUrl() ?>" method="post" id="user_forgotpassword_form" class="nav__list-inner">
        <p class="form-notice"><?php echo $this->__('Please enter your email below and we will send you a new password.') ?></p>
        <p class="form__field form__field--required">
            <!--<label for="email_address" class="form__label form__label--required"><?php echo $this->__('Email Address') ?></label>-->
            <input type="email" placeholder="Email Address" class="form__textfield textfield validate-email required-entry" name="email" id="email_address" value="<?php echo $this->htmlEscape($this->getEmailValue()) ?>" title="<?php echo $this->__('Email Address') ?>">
        </p><!-- .form__field -->
        <?php echo $this->getChildHtml('form.additional.info'); ?>
        <p class="form__submit-wrapper">
            <button type="submit" title="<?php echo $this->__('Submit') ?>" class="form__submit button continue" onclick="window.customerAccount.forgot()"><?php echo $this->__('Submit') ?></button>
        </p><!-- .form__submit-wrapper -->
    </form>
    <script type="text/javascript">
        //<![CDATA[
        if (typeof window.customerAccount != 'undefined') {
            window.customerAccount.setForgotForm('user_forgotpassword_form');
            window.customerAccount.setForgotTitle(<?php echo Zend_Json::encode($this->__('Forgot Your Password?'));?>);
        }
        //]]>
    </script>
</div>