<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Mobile2
 * @version    2.0.2
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><div class="newsletter-subscription">
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php echo $this->getChildHtml('form_before')?>
<form action="<?php echo $this->getAction() ?>" method="post" class="form" id="form-validate">
    <?php echo $this->getBlockHtml('formkey')?>
    <div class="form__field form__field--required">
        <ul class="form__checkboxes">
            <li class="form__checkboxes-item">
                <input type="checkbox" name="is_subscribed" id="subscription" value="1" title="<?php echo $this->__('General Subscription') ?>"<?php if($this->getIsSubscribed()): ?> checked="checked"<?php endif; ?> class="form__checkbox">
                <label class="form__checkbox-label" for="subscription">
                    <?php echo $this->__('General Subscription') ?>
                </label>
            </li>
        </ul>
    </div><!-- .form__field -->
    <p class="form__submit-wrapper">
        <button type="submit" title="<?php echo $this->__('Save') ?>" class="form__submit button continue-another"><span><span><?php echo $this->__('Save') ?></span></span></button>
    </p><!-- .form__submit-wrapper -->
</form>
    <script type="text/javascript">
        //<![CDATA[
        var dataForm = new VarienForm('form-validate', true);
        //]]>
    </script>
</div>