<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Mobile2
 * @version    2.0.2
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><div class="account-info">
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <form action="<?php echo $this->getUrl('*/*/resetpasswordpost', array('_query' => array('id' => $this->getCustomerId(), 'token' => $this->getResetPasswordLinkToken()))); ?>" method="post" id="form-validate">
        <div class="fieldset">
            <p class="form__field form__field--required">
                <label for="password" class="form__label form__label--required"><?php echo $this->__('New Password') ?></label>
                <input type="password" class="form__textfield textfield validate-password required-entry" name="password" id="password" title="<?php echo $this->__('New Password') ?>">
            </p><!-- .form__field -->
            <p class="form__field form__field--required">
                <label for="confirmation" class="form__label form__label--required"><?php echo $this->__('Confirm New Password') ?></label>
                <input type="password" class="form__textfield textfield validate-cpassword required-entry" name="confirmation" id="confirmation" title="<?php echo $this->__('Confirm New Password') ?>">
            </p><!-- .form__field -->
        </div>
        <p class="form__submit-wrapper">
            <span class="required">
                <?php echo $this->__('Required Fields') ?>
            </span>
            <button type="submit" title="<?php echo $this->__('Reset a Password') ?>" class="form__submit button continue"><?php echo $this->__('Reset a Password') ?></button>
        </p><!-- .form__submit-wrapper -->
    </form>
    <script type="text/javascript">
        //<![CDATA[
        var dataForm = new VarienForm('form-validate', true);
        //]]>
    </script>
</div>