<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Mobile2
 * @version    2.0.2
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><?php
$_order  = $this->getOrder();
$_source = $this->getSource();
$_fullInfo = $_order->getFullTaxInfo();
global $taxIter; $taxIter++;
?>
<?php  ?>

<?php if ($this->displayFullSummary()): ?>
    <?php $isTop = 1; ?>
    <?php if ($_fullInfo) foreach ($_fullInfo as $info): ?>
        <?php if (isset($info['hidden']) && $info['hidden']) continue; ?>
        <?php
        $percent    = $info['percent'];
        $amount     = $info['amount'];
        $rates      = $info['rates'];
        $isFirst    = 1;
        ?>
        <?php foreach ($rates as $rate): ?>
            <tr class="summary-details-<?php echo $taxIter; ?> summary-details<?php if ($isTop): echo ' summary-details-first'; endif; ?>"<?php if (!$this->getIsPlaneMode()):?> style="display:none;"<?php endif;?>>
                <th <?php echo $this->getLabelProperties()?>>
                    <?php echo $this->escapeHtml($rate['title']); ?>
                    <?php if (!is_null($rate['percent'])): ?>
                        (<?php echo (float)$rate['percent']; ?>%)
                    <?php endif; ?>
                    <br />
                </th>
                <?php if ($isFirst): ?>
                    <td <?php echo $this->getValueProperties()?> rowspan="<?php echo count($rates); ?>">
                        <?php echo $_order->formatPrice($amount); ?>
                    </td>
                <?php endif; ?>
            </tr>
            <?php $isFirst = 0; ?>
            <?php $isTop = 0; ?>
        <?php endforeach; ?>
    <?php endforeach; ?>
<?php endif;?>

<?php if ($this->displayFullSummary() && $_fullInfo && !$this->getIsPlaneMode()): ?>
<tr class="summary-total" onclick="expandDetails(this, '.summary-details-<?php echo $taxIter;?>')">
    <?php elseif ($this->displayFullSummary() && $_fullInfo && $this->getIsPlaneMode()): ?>
<tr class="show-details">
    <?php else: ?>
<tr>
    <?php endif; ?>
    <th <?php echo $this->getLabelProperties()?>>
        <?php if ($this->displayFullSummary()): ?>
            <div class="summary-collapse"><?php echo $this->__('Tax'); ?></div>
        <?php else: ?>
            <?php echo $this->__('Tax'); ?>
        <?php endif;?>
    </th>
    <td <?php echo $this->getValueProperties()?>><?php echo $_order->formatPrice($_source->getTaxAmount()) ?></td>
</tr>