<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Mobile2
 * @version    2.0.2
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><?php
/**
 * Create account form template
 *
 * @see Enterprise_Customer_Block_Form_Renderer_Date
 */
/* @var $this Enterprise_Customer_Block_Form_Renderer_Date */
?>
<div class="form__field<?php if ($this->isRequired()): ?> form__field--required<?php endif; ?>">
    <label for="<?php echo $this->getHtmlId('month')?>" class="form__label<?php if ($this->isRequired()): ?> form__label--required<?php endif; ?>"><?php echo $this->getLabel() ?></label>
    <div class="input-box customer-dob">
        <?php
        $this->setDateInput('d',
            '<span class="dob-day">
                 <input type="text" id="' . $this->getHtmlId('day') . '" value="' . $this->getDay() . '" title="' . $this->__('Day') . '" class="input-text" />
             <label for="' . $this->getHtmlId('day') . '">' . $this->__('DD') . '</label>
         </span>'
        );

        $this->setDateInput('m',
            '<span class="dob-month">
                 <input type="text" id="' . $this->getHtmlId('month') . '" value="' . $this->getMonth()  . '" title="' . $this->__('Month')  . '" class="input-text" />
             <label for="' . $this->getHtmlId('month') . '">' . $this->__('MM')  . '</label>
         </span>'
        );

        $this->setDateInput('y',
            '<span class="dob-year">
                 <input type="text" id="' . $this->getHtmlId('year') . '" value="' . $this->getYear()  . '" title="' . $this->__('Year')  . '" class="input-text" />
             <label for="' . $this->getHtmlId('year') . '">' . $this->__('YYYY')  . '</label>
         </span>'
        );
        ?>
        <?php echo $this->getSortedDateInputs() ?>
        <span class="dob-full" style="display:none;">
        <input type="hidden" id="<?php echo $this->getHtmlId('full')?>" name="<?php echo $this->getFieldName()?>" />
    </span>
        <div style="clear:both"></div>
        <div class="validation-advice" id="<?php echo $this->getHtmlId('date-advice')?>" style="opacity:0.999999; display:none;"></div>
        <?php if ($_message = $this->getAdditionalDescription()) : ?>
            <div class="validation-advice"><?php echo $_message; ?></div>
        <?php endif; ?>
    </div>
    <script type="text/javascript">
        //<![CDATA[
        var dateRange = new Varien.dateRangeDate('id', '<?php echo $this->getHtmlId('')?>', <?php echo ($this->isRequired() ? 'true' : 'false'); ?>, '<?php echo $this->getDateFormat() ?>');
        dateRange.setDateRange(<?php echo $this->getMinDateRange()?>, <?php echo $this->getMaxDateRange()?>);
        //]]>
    </script>
</div>