<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Mobile2
 * @version    2.0.2
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><?php
/**
 * Create account form template
 *
 * @see Enterprise_Customer_Block_Form_Renderer_Multiline
 */
/* @var $this Enterprise_Customer_Block_Form_Renderer_Multiline */
?>
<div class="form__field<?php if ($this->isRequired()): ?> form__field--required<?php endif; ?>">
    <label for="<?php echo $this->getHtmlId(0)?>" class="form__label<?php if ($this->isRequired()): ?> form__label--required<?php endif; ?>"><?php echo $this->getLabel() ?></label>
    <input type="text" id="<?php echo $this->getHtmlId(0)?>" name="<?php echo $this->getFieldName('')?>" value="<?php echo $this->getEscapedValue(0) ?>" class="form__textfield textfield<?php echo $this->getHtmlClass(); ?>" />
    <?php $_message = $this->getAdditionalDescription(); ?>
    <?php if ($this->getLineCount() == 1 && $_message) : ?>
        <div class="validation-advice"><?php echo $_message; ?></div>
    <?php endif; ?>
    <?php if ($this->getLineCount() > 1): ?>
        <?php for ($i = 1, $lc = $this->getLineCount(); $i < $lc; $i ++): ?>
            <input type="text" id="<?php echo $this->getHtmlId($i)?>" name="<?php echo $this->getFieldName('')?>" value="<?php echo $this->getEscapedValue($i) ?>" class="form__textfield textfield<?php echo $this->getLineHtmlClass();?>" />
            <?php if ($this->getLineCount() == $i+1 && $_message) : ?>
                <div class="validation-advice"><?php echo $_message; ?></div>
            <?php endif; ?>
        <?php endfor; ?>
    <?php endif;?>
</div>