<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Mobile2
 * @version    2.0.2
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><?php
/**
 * Create account form template
 *
 * @see Enterprise_Customer_Block_Form_Renderer_Select
 */
/* @var $this Enterprise_Customer_Block_Form_Renderer_Select */
?>
<div class="form__field<?php if ($this->isRequired()): ?> form__field--required<?php endif; ?>">
    <label for="<?php echo $this->getHtmlId()?>" class="form__label<?php if ($this->isRequired()): ?> form__label--required<?php endif; ?>"><?php echo $this->getLabel() ?></label>
    <select id="<?php echo $this->getHtmlId()?>" name="<?php echo $this->getFieldName()?>" class="form__select validate-select <?php echo $this->getHtmlClass();?>">
        <?php foreach ($this->getOptions() as $option):?>
            <option value="<?php echo $option['value']?>"<?php if ($option['value'] == $this->getValue()):?> selected="selected"<?php endif;?>><?php echo $this->htmlEscape($option['label'])?></option>
        <?php endforeach;?>
    </select>
    <?php if ($_message = $this->getAdditionalDescription()) : ?>
        <div class="validation-advice"><?php echo $_message; ?></div>
    <?php endif; ?>
</div>