<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Mobile2
 * @version    2.0.2
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><?php
/**
 * Create account form template
 *
 * @see Enterprise_Customer_Block_Form_Renderer_Image
 */
/* @var $this Enterprise_Rma_Block_Form_Renderer_Image */
?>
<div class="form__field">
    <a href="<?php echo $this->getImageUrl() ?>" target="_blank" >
        <img height="15" class="small-image-preview v-middle" src="<?php echo $this->getImageUrl() ?>" title="View Full Size" alt="View Full Size">
    </a>
</div>
