<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Mobile2
 * @version    2.0.2
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><div class="my-orders" id="customer_order_list">
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <?php $_orders = $this->getOrders(); ?>
    <?php if($_orders->getSize()): ?>
        <?php foreach ($_orders as $_order): ?>
            <div class="island">
                <div><?php echo $this->__('Order #');?></div>
                <div>
                    <a href="<?php echo $this->getViewUrl($_order) ?>" class="my-orders__link"><?php echo $_order->getRealOrderId() ?></a>
                </div>
                <div><?php echo $this->__('Date');?></div>
                <div><?php echo $this->formatDate($_order->getCreatedAtStoreDate()) ?></div>
                <div><?php echo $this->__('Total');?></div>
                <div><?php echo $_order->formatPrice($_order->getGrandTotal()) ?></div>
            </div>
        <?php endforeach; ?>
    <!--table id="order_history_data" class="my-orders__list">
        <tbody>
            <?php foreach ($_orders as $_order): ?>
                <tr class="my-orders__item">
                    <th class="my-orders__number"><a href="<?php echo $this->getViewUrl($_order) ?>" class="my-orders__link"><?php echo $_order->getRealOrderId() ?></a></th>
                    <td class="my-orders__date"><?php echo $this->formatDate($_order->getCreatedAtStoreDate()) ?></td>
                    <td class="my-orders__price"><?php echo $_order->formatPrice($_order->getGrandTotal()) ?></td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table-->
    <?php else: ?>
        <p><?php echo $this->__('You have placed no orders.'); ?></p>
    <?php endif ?>
</div>
<?php echo $this->getPagerHtml(); ?>
<script type="text/javascript">
    //<![CDATA[
    if (typeof pager != 'undefined') {
        pager.containerId = 'customer_order_list';
        pager.tableId = 'order_history_data';
    }
    //]]>
</script>