<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Mobile2
 * @version    2.0.2
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><div class="order" style="padding:0">
    <?php  $_order = $this->getOrder() ?>
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <div class="order__section-top">
        <?php echo $this->getChildHtml('buttons') ?>
        <p class="order__reorder"><a href="<?php echo $this->getReorderUrl($_order) ?>"><?php echo $this->__('Reorder') ?></a></p>
        <p class="order__date"><?php echo $this->__('Order Date: %s', $this->formatDate($_order->getCreatedAtStoreDate(), 'long')) ?></p>
    </div>
    <?php if (!$_order->getIsVirtual()): ?>
        <div class="order__section">
            <h2 class="order__section-title"><?php echo $this->__('Shipping Address') ?></h2>
            <address class="order__address">
                <?php echo $_order->getShippingAddress()->format('html') ?>
            </address>
        </div>
        <div class="order__section">
            <h2 class="order__section-title"><?php echo $this->__('Shipping Method') ?></h2>
            <?php if ($_order->getShippingDescription()): ?>
                <span class="order__shipping-method"><?php echo $_order->getShippingDescription() ?></span>
            <?php else: ?>
                <span class="order__shipping-method"><?php echo $this->helper('sales')->__('No shipping information available'); ?></span>
            <?php endif; ?>
        </div>
    <?php endif; ?>
    <div class="order__section">
        <h2 class="order__section-title"><?php echo $this->__('Billing Address') ?></h2>
        <address class="order__address">
            <?php echo $_order->getBillingAddress()->format('html') ?>
        </address>
    </div>
    <div class="order__section">
        <h2 class="order__section-title"><?php echo $this->__('Payment Method') ?></h2>
        <span class="order__payment-method"><?php echo $this->getPaymentInfoHtml() ?></span>
    </div>
    <?php echo $this->getChildHtml('sales.order.view') ?>
</div>