<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Mobile2
 * @version    2.0.2
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?>
<?php $_item = $this->getItem()?>
<div class="shopping-cart__item">
    <div class="shopping-cart__product product-card">
        <p class="product-card__image-wrapper">
                    <img class="product-card__image" alt="<?php echo $this->htmlEscape($this->getProductName()) ?>" src="<?php echo $this->getProductThumbnail()->resize(90); ?>">
        </p>
        <div class="product-card__info">
            <h3 class="product-card__title">
                    <?php echo $this->htmlEscape($this->getProductName()) ?>
                <p class="product-card__size"></p>
            </h3>
            <div class="product-card__selected-options">
                <p class="product-card__price">
                    <?php if (Mage::helper('weee')->typeOfDisplay($_item, array(0, 1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                        <?php echo $this->helper('checkout')->formatPrice($_item->getCalculationPrice()+$_item->getWeeeTaxAppliedAmount()+$_item->getWeeeTaxDisposition()); ?>
                    <?php else: ?>
                        <?php echo $this->helper('checkout')->formatPrice($_item->getCalculationPrice()) ?>
                    <?php endif; ?>
                </p>
                <p class="product-original__price"></p>               
            </div>
        </div>
        <div class="shopping-item-controls">
        	<button class="add-to-cart__l">-</button>
            <input type="text" class="add-to-cart__quantity input-text" name="cart[<?php echo $_item->getId() ?>][qty]" value="<?php echo $this->getQty() ?>" size="4" maxlength="12" readonly/>
            <button class="add-to-cart__r">+</button>
            <!--<button type="button" onclick="window.updateCart.submit();" title="<?php echo $this->__('Update Cart') ?>" class="cart-update"><span class="triangle-left"></span><?php echo $this->__('Update Cart') ?></button>-->
            <button type="button" class="shopping-cart__delete js-delete-product-from-cart" onclick="window.updateCart<?php echo $this->getItem()->getId()?>.submit()"><span><?php echo $this->__('Delete') ?></span></button>        
    	</div>
    </div>
    
</div>
<script type="text/javascript">
    //<![CDATA[
    window.updateCart<?php echo $this->getItem()->getId()?> = new awMobile2.app.AjaxUpdater(null,'<?php echo $this->helper('aw_mobile2/url')->getCartDeleteUrl($this->getItem()->getId())?>');
    $$('.add-to-cart__quantity').each(function(el){
        el.observe('focus', function(e) {
            var el = e.target;
            el.up().select('.shopping-cart__delete').first().hide();
            var editBtn = el.up().select('.shopping-item-edit-link').first();
            if (editBtn) {
                editBtn.hide();
            }
        });
        el.observe('blur', function(e) {
            var el = e.target;
            el.up().select('.shopping-cart__delete').first().show();
            var editBtn = el.up().select('.shopping-item-edit-link').first();
            if (editBtn) {
                editBtn.show();
            }
        });
    });
    //]]>
</script>