<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Mobile2
 * @version    2.0.2
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><?php if ($this->showPrefix()): ?>
    <p class="form__field  <?php if ($this->isPrefixRequired()) echo ' form__label--required' ?>">
        <label class="form__label <?php if ($this->isPrefixRequired()) echo ' form__label--required' ?>">
            <?php echo $this->__('Prefix') ?>
        </label>
        <?php if ($this->getPrefixOptions()===false): ?>
            <input type="text" id="<?php echo $this->getFieldId('prefix')?>" name="<?php echo $this->getFieldName('prefix')?>" value="<?php echo $this->htmlEscape($this->getObject()->getPrefix()) ?>" title="<?php echo $this->__('Prefix') ?>" class="form__textfield textfield <?php if ($this->isPrefixRequired()):?> required-entry<?php endif; ?>" <?php echo $this->getFieldParams() ?>/>
        <?php else: ?>
            <select id="<?php echo $this->getFieldId('prefix')?>" name="<?php echo $this->getFieldName('prefix')?>" title="<?php echo $this->__('Prefix') ?>"<?php if ($this->isPrefixRequired()):?> class="required-entry"<?php endif; ?> <?php echo $this->getFieldParams() ?>>
                <?php foreach ($this->getPrefixOptions() as $_option): ?>
                    <option value="<?php echo $_option?>"<?php if ($this->getObject()->getPrefix()==$_option):?> selected="selected"<?php endif; ?>><?php echo $this->__($_option)?></option>
                <?php endforeach ?>
            </select>
        <?php endif; ?>
    </p><!-- .form__field -->
<?php endif; ?>
<p class="form__field form__field--required">
    <!--<label class="form__label form__label--required"><?php echo $this->__('First Name') ?></label>-->
    <input type="text" placeholder="First Name" class="form__textfield textfield required-entry" id="<?php echo $this->getFieldId('firstname')?>" name="<?php echo $this->getFieldName('firstname')?>" value="<?php echo $this->htmlEscape($this->getObject()->getFirstname()) ?>" title="<?php echo $this->__('First Name') ?>" <?php echo $this->getFieldParams() ?>>
</p><!-- .form__field -->
<?php if ($this->showMiddlename()): ?>
    <p class="form__field">
        <label class="form__label"><?php echo $this->__('M.I.') ?></label>
        <input type="text" class="form__textfield textfield" id="<?php echo $this->getFieldId('middlename')?>" name="<?php echo $this->getFieldName('middlename')?>" value="<?php echo $this->htmlEscape($this->getObject()->getMiddlename()) ?>" title="<?php echo $this->__('M.I.') ?>" <?php echo $this->getFieldParams() ?>>
    </p><!-- .form__field -->
<?php endif; ?>
<p class="form__field form__field--required">
    <!--<label class="form__label form__label--required"><?php echo $this->__('Last Name') ?></label>-->
    <input type="text" placeholder="Last Name" class="form__textfield textfield required-entry" id="<?php echo $this->getFieldId('lastname')?>" name="<?php echo $this->getFieldName('lastname')?>" value="<?php echo $this->htmlEscape($this->getObject()->getLastname()) ?>" title="<?php echo $this->__('Last Name') ?>" <?php echo $this->getFieldParams() ?>>
</p><!-- .form__field -->
<?php if ($this->showSuffix()): ?>
    <p class="form__field <?php if ($this->isSuffixRequired()) echo ' form__label--required' ?>">
        <label class="form__label <?php if ($this->isSuffixRequired()) echo ' form__label--required' ?>">
            <?php echo $this->__('Suffix') ?>
        </label>
        <?php if ($this->getSuffixOptions()===false): ?>
            <input type="text" id="<?php echo $this->getFieldId('suffix')?>" name="<?php echo $this->getFieldName('suffix')?>" value="<?php echo $this->htmlEscape($this->getObject()->getSuffix()) ?>" title="<?php echo $this->__('Suffix') ?>" class="form__textfield textfield <?php if ($this->isSuffixRequired()):?> required-entry<?php endif; ?>" <?php echo $this->getFieldParams() ?>/>
        <?php else: ?>
            <select id="<?php echo $this->getFieldId('suffix')?>" name="<?php echo $this->getFieldName('suffix')?>" title="<?php echo $this->__('Suffix') ?>"<?php if ($this->isSuffixRequired()):?> class="required-entry"<?php endif; ?> <?php echo $this->getFieldParams() ?>>
                <?php foreach ($this->getSuffixOptions() as $_option): ?>
                    <option value="<?php echo $_option?>"<?php if ($this->getObject()->getSuffix()==$_option):?> selected="selected"<?php endif; ?>><?php echo $this->__($_option)?></option>
                <?php endforeach ?>
            </select>
        <?php endif; ?>
    </p>
<?php endif; ?>