<header id="breadcrumbs" class="page-header">
    <?php if($crumbs && is_array($crumbs)): ?>
        <?php foreach($crumbs as $_crumbInfo): ?>
            <?php if (!$_crumbInfo['last']):?>
                <?php $firstLink = $_crumbInfo;?>
            <?php else:?>
                <?php $lastLink = $_crumbInfo;?>
            <?php endif; ?>
        <?php endforeach; ?>
            <a href="javascript:history.back();" title="<?php echo $this->htmlEscape($firstLink['title']) ?>" class="page-header__action page-header__action--left  product-view-breadcrumbs">
                <span class="page-header__action--back"></span>
                <span class="title">
				&nbsp;
                    <?php //echo $this->htmlEscape($firstLink['label']) ?>
                </span>
            </a>
    <?php endif; ?>
<?php echo $this->getChildHtml('category.top');?>
</header>
<script type="text/javascript">
    if ($('category_title')) {
        setTitleMargin($('category_title'));
    }
</script>