<?php
$_category  = $this->getCurrentCategory();
$_helper    = $this->helper('catalog/output');
$layerBlock = $this->getLayout()->getBlock('catalog.layer');
if ($layerBlock) {
    $layerBlock->setCategory($_category);
}
$toolbarBlock = $this->getLayout()->getBlock('product_list_toolbar_top');
if ($toolbarBlock) {
    $toolbarBlock->setCategory($_category);
}
?>
<h1 id="category_title" class="page-header__title"><span><?php echo $_helper->categoryAttribute($_category, $_category->getName(), 'name') ?></span></h1>
<div class="category__filter category-filter">
    <?php echo $this->getChildHtml('product_list_toolbar_top')?>
    <?php //echo $this->getChildHtml('catalog_layer_nav')?>
</div>