<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Mobile2
 * @version    2.0.2
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><ul class="filter__list-inner">
    <li class="nav__item filter__item filter__item--parameter all">
        <span class="filter__item-title nav__item-title">
            <span class="clear">
                <?php echo $this->__('Clear all filter') ?>
            </span>
        </span>
    </li>
    <?php foreach ($this->getItems() as $_item): ?>
        <li data-request-var="<?php echo $_item->getFilter()->getRequestVar();?>" value="<?php echo $_item->getValue();?>" class="nav__item filter__item filter__item--parameter">
            <span class="filter__item-title nav__item-title radio"><?php echo $_item->getLabel(); ?></span>
        </li>
    <?php endforeach ?>
</ul>