<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Mobile2
 * @version    2.0.2
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><?php $_filters = $this->getActiveFilters() ?>
<?php if(!empty($_filters)): ?>
    <li class="nav__item filter__item filter__item--parameter all">
        <span class="filter__item-title nav__item-title">
            <span class="clear js-filter-clear">
                <?php echo $this->__('Clear all filter') ?>
            </span>
        </span>
    </li>
    <?php foreach ($_filters as $_filter): ?>
        <li data-request-var="<?php echo $_filter->getFilter()->getRequestVar()?>" value="<?php echo $_filter->getFilter()->getResetValue();?>" class="nav__item filter__item filter__item--state filter__item--parameter">
            <a class="filter__item-title nav__item-title" href="javascript:void(0)"><?php echo $_filter->getName() ?>
                <span class="filter__item-clear"><?php echo $this->__('Clear');?></span>
                <span data-default-title="<?php echo $this->__('Filter By');?>" class="selected-option">
                    <span class="default-option-title"><?php echo $this->__('Filter By');?>: <span class="option-label"><?php echo $_filter->getLabel()?></span></span>
                </span>
            </a>
        </li>
    <?php endforeach; ?>
<?php endif; ?>