<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Mobile2
 * @version    2.0.2
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><div class="discount__field coupon">
    <form class="form" id="discount-coupon-form" action="<?php echo $this->helper('aw_mobile2/url')->getCartCouponPostUrl() ?>" method="post">
        <label class="discount__field-label"><?php echo $this->__("Coupon Code")?></label>
        <input type="text" class="discount__textfield textfield" id="coupon_code" name="coupon_code" value="<?php echo $this->htmlEscape($this->getCouponCode()) ?>">
        <input type="hidden" name="remove" id="remove-coupone" value="0" />
        <p class="discount__submit-wrapper">
            <button class="discount__submit js-apply-discount" type="button" title="<?php echo $this->__('Apply Coupon') ?>" class="button" style="background-color:#F4A137;" onclick="window.discountForm.submit(false)" value="<?php echo $this->__('Apply Coupon') ?>"><?php echo $this->__('Apply Coupon') ?></button>
            <?php if(strlen($this->getCouponCode())): ?>
                <button class="discount__submit js-apply-discount" type="button" title="<?php echo $this->__('Cancel Coupon') ?>" class="button" style="background-color:#F4A137;" onclick="window.discountForm.submit(true)" value="<?php echo $this->__('Cancel Coupon') ?>"><?php echo $this->__('Cancel Coupon') ?></button>
            <?php endif;?>
        </p>
    </form>
    <script type="text/javascript">
        //<![CDATA[
        window.discountForm = new VarienForm('discount-coupon-form');
        window.discountForm.submit = function (isRemove) {
            if (isRemove) {
                $('coupon_code').removeClassName('required-entry');
                $('remove-coupone').value = "1";
            } else {
                $('coupon_code').addClassName('required-entry');
                $('remove-coupone').value = "0";
            }
            if (!this.validator.validate()) {
                return false;
            }
            window.updateCoupon = new awMobile2.app.AjaxUpdater('discount-coupon-form', null);
            window.updateCoupon.submit();
        };
        //]]>
    </script>
</div>