<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Mobile2
 * @version    2.0.2
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><?php echo $this->getChildHtml('title'); ?>
<div class="cart-top-container panel__container">
    <div class="page-scroll-wrapper">
        <div class="page-scroll">
            <div class="page-content">
                <div class="shopping-cart">
                    <div class="shopping-cart__items">
                        <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
                        <p><?php echo $this->__('You have no items in your shopping cart.') ?></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
