<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Mobile2
 * @version    2.0.2
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><?php
/**
 * @see Enterprise_GiftCardAccount_Block_Check
 */
?>
<?php $card = $this->getCard() ?>
<?php if ($card->getId()): ?>
    <div class="gift-card-info">
        <div class="gift-card-info-item">
            <span class="title"><?php echo $this->__("Gift Card:"); ?></span>
            <span class="value"><?php echo $this->__("%s", $card->getCode()); ?></span>
        </div>
        <div class="gift-card-info-item">
            <span class="title"><?php echo $this->__("Current Balance:"); ?></span>
            <span class="value"><?php echo $this->__("%s", Mage::helper('core')->currency($card->getBalance())); ?></span>
        </div>
        <?php if ($card->getDateExpires()): ?>
            <div class="gift-card-info-item">
                <span class="title"><?php echo $this->__("Expires:"); ?></span>
                <span class="value"><?php echo $this->__("%s", $this->formatDate($card->getDateExpires(), 'short')); ?></span>
            </div>
        <?php endif; ?>
    </div>
<?php else: ?>
<div class="gift-card-info">
    <div class="gift-card-info-item">
        <span class="title"><?php echo $this->__('Wrong or expired Gift Card Code.'); ?></span>
    </div>
</div>
<?php endif; ?>
<div style="clear:both"></div>
