<?php $menuHelper = Mage::helper('megamenu'); ?>
<div class="fixed-header-area fixed-menu-type hidden-xs">
    <div class="fixed-header">
        <div class="container">
            <div class="menu-wrapper">
                <div class="menu-icon hidden-md hidden-lg"><i class="fa fa-bars"></i></div>
                <div class="logo-with-menu">
                    <?php if ($menuHelper->getIsHomePage()):?>
                    <h1 class="logo"><strong><?php echo $menuHelper->getLogoAlt() ?></strong><a href="<?php echo $this->getUrl('') ?>" title="<?php echo $menuHelper->getLogoAlt() ?>"><img src="<?php echo $menuHelper->getLogoSrc() ?>" alt="<?php echo $menuHelper->getLogoAlt() ?>" /></a></h1>
                    <?php else:?>
                        <a href="<?php echo $this->getUrl('') ?>" title="<?php echo $menuHelper->getLogoAlt() ?>" class="logo"><strong><?php echo $menuHelper->getLogoAlt() ?></strong><img src="<?php echo $menuHelper->getLogoSrc() ?>" alt="<?php echo $menuHelper->getLogoAlt() ?>" /></a>
                    <?php endif?>
                </div>
                <div class="modal-buttons">
                    <a href="<?php echo $this->getUrl('checkout/cart') ?>" class="shopping-cart-link hidden-md hidden-lg">&nbsp;</a>
                    <a href="<?php echo $this->getUrl('customer/account')?>" class="my-account-link hidden-md hidden-lg">&nbsp;</a>
                    <a href="#" data-toggle="modal" data-target="#searchModal" class="search-link hidden-md hidden-lg">&nbsp;</a>
                </div>
                <div class="menu-all-pages-container">
                    <ul class="menu">
                        <?php echo $menuHelper->getMenuContent(); ?>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>