<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Mobile2
 * @version    2.0.2
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?>
<div class="add_to_cart_all_l">
<?php $summaryQty = (int)Mage::getSingleton('checkout/cart')->getSummaryQty();?>
        <a id="shopping_cart" href="javascript:void(0)" class="header__link header__link--cart<?php echo ($summaryQty == 0)?" header__link--cart-empty":"";?>">
            <?php if ($summaryQty > 0):?>
                <span class="items-in-cart"><?php echo $summaryQty;?></span>
            <?php endif;?>
        </a>
<?php $_product = $this->getProduct() ?>
<p>
    <input type="hidden" value="<?php echo max($this->getMinimalQty($_product), 1) ?>" class="add-to-cart__quantity" name="qty">
    <button type="button" class="button add-to-cart__submit js-add-to-cart green-button" onclick="window.productAddToCartForm.submit()">
        <?php if($_product->getHasOptions()): ?>
            <?php echo $this->__('Configure and Buy');?>
        <?php else: ?>
            <?php echo $this->__('Add to cart');?>
        <?php endif;?>
    </button>
</p>
</div>