<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Mobile2
 * @version    2.0.2
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><?php if($crumbs && is_array($crumbs)): ?>
    <?php foreach($crumbs as $_crumbInfo): ?>
        <?php if (!$_crumbInfo['last']):?>
            <?php $firstLink = $_crumbInfo;?>
        <?php endif; ?>
    <?php endforeach; ?>
    <?php
        $backUrl = Mage::getSingleton('customer/session')->getMobileBackData();
        if ($backUrl) {
            $firstLink['link'] = $backUrl['url'];
            $firstLink['title'] = $backUrl['title'];
            $firstLink['label'] = $backUrl['title'];
            Mage::getSingleton('customer/session')->setMobileBackData(null);
        }
            $firstLink['label'] = '&nbsp;&nbsp;';
    ?>
    <a href="javascript:history.back();" title="<?php echo $this->htmlEscape($firstLink['title']) ?>" class="page-header__action page-header__action--left  product-view-breadcrumbs">
            <span class="page-header__action--back"></span>
            <span class="title">
                <?php echo $this->htmlEscape($firstLink['label']) ?>
            </span>
    </a>
    <!--<header id="breadcrumbs" class="page-header">
        
        <?php
            $_product = Mage::registry('current_product');
            $_helper = $this->helper('catalog/output');
        ?>
        <h1 id="product_title" class="page-header__title"><span><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name')?></span></h1>
    </header>--><!-- .page-header -->
    <script type="text/javascript">
        setTitleMargin($('product_title'));
    </script>
<?php endif; ?>
