<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Mobile2
 * @version    2.0.2
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><?php if (count($this->getGalleryImages()) > 0): ?>
    <?php $mainImageBigSrc = $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail')->resize(580, 400)->__toString(); ?>
    <?php $mainImageSmallSrc = $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail')->resize(114, 114)->__toString(); ?>
    <div class="gallery-container">
        <div>
            <div class="slider-container">
                <div class="product__gallery gallery" id="product_gallery">
                    <div class="product__gallery-image">
                        <img src="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'small_image')->resize(580, 400); ?>" alt="<?php echo $this->htmlEscape($this->getProduct()->getName()) ?>" title="<?php echo $this->htmlEscape($this->getProduct()->getName()) ?>" />
                    </div>
                    <?php foreach ($this->getGalleryImages() as $_image): ?>
                        <?php $_imgSrc = $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->resize(580, 400)->__toString();?>
                        <?php if($mainImageBigSrc != $_imgSrc):?>
                            <div class="product__gallery-image">
                                <img src="<?php echo $_imgSrc; ?>" alt="<?php echo $this->htmlEscape($_image->getLabel()) ?>" title="<?php echo $this->htmlEscape($_image->getLabel()) ?>" />
                            </div>
                        <?php endif;?>
                    <?php endforeach; ?>

                </div>
                <div id="gallery_slider_bullets" class="gallery-full-screen-control">
                    <a title="<?php echo $this->htmlEscape($_image->getLabel()) ?>" href="javascript:void(0);" class="gallery-slider-bullet">#</a>
                    <?php foreach ($this->getGalleryImages() as $_image): ?>
                        <?php $_imgSrc = $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->resize(114, 114)->__toString();?>
                        <?php if($mainImageSmallSrc != $_imgSrc):?>
                            <a title="<?php echo $this->htmlEscape($_image->getLabel()) ?>" href="javascript:void(0);" class="gallery-slider-bullet">#</a>
                        <?php endif;?>
                    <?php endforeach; ?>
                </div>
                <div id="gallery_slider_bullets_img">
                    <div>
                        <img src="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'small_image')->resize(114, 114); ?>" alt="<?php echo $this->htmlEscape($this->getProduct()->getName()) ?>" title="<?php echo $this->htmlEscape($this->getProduct()->getName()) ?>" />
                    </div>
                    <?php foreach ($this->getGalleryImages() as $_image): ?>
                        <?php $_imgSrc = $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->resize(114, 114)->__toString();?>
                        <?php if($mainImageSmallSrc != $_imgSrc):?>
                            <div>
                                <img src="<?php echo $_imgSrc; ?>" alt="<?php echo $this->htmlEscape($_image->getLabel()) ?>" title="<?php echo $this->htmlEscape($_image->getLabel()) ?>" />
                            </div>
                        <?php endif;?>
                    <?php endforeach; ?>
                </div>
            </div>
        </div>
    </div>
    <script type="text/javascript">
        var ProductMobileMediaGallery = new awMobile2.app.mediaGallery('product_gallery', '.gallery-slider-bullet', <?php echo Zend_Json::encode($this->helper('catalog/output')->productAttribute($this->getProduct(), $this->getProduct()->getName(), 'name'));?>, <?php echo Zend_Json::encode($this->__('Close'));?>);
    </script>
<?php endif; ?>