<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Mobile2
 * @version    2.0.2
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><div class="product__tabs tabs">
    <div class="tabs__labels-wrapper">
        <ul class="tabs__labels">
            <?php foreach ($this->getTabs() as $_index => $_tab): ?>
                <?php if($this->getChildHtml($_tab['alias'])): ?>
                    <li id="product_tabs_<?php echo $_tab['alias'] ?>" class="tabs__label <?php echo !$_index ? 'is-current' : '';?>"><span class="tab-title"><?php echo $_tab['title']?></span></li>
                <?php endif; ?>
            <?php endforeach; ?>
        </ul>
    </div>
    <div class="tabs__container">
        <?php foreach ($this->getTabs() as $_index => $_tab): ?>
            <?php if($this->getChildHtml($_tab['alias'])): ?>
                <section id="product_tabs_<?php echo $_tab['alias'] ?>_contents" class="product__<?php echo $_tab['alias'] ?> <?php echo $_tab['alias'] ?> tabs__tab""><?php echo $this->getChildHtml($_tab['alias']) ?></section>
            <?php endif; ?>
        <?php endforeach; ?>
    </div>
</div>
<script type="text/javascript">
    //<![CDATA[
    Varien.Tabs = Class.create();
    Varien.Tabs.prototype = {
        initialize: function(selector) {
            var self=this;
            if ($$(selector+' li').length <= 1) {
                $$(selector).first().hide();
            }
            $$(selector+' li').each(this.initTab.bind(this));
        },

        initTab: function(el) {
            if (el.hasClassName('is-current')) {
                this.showContent(el);
            }
            el.observe('click', this.showContent.bind(this, el));
        },

        showContent: function(li) {
            var ul = $(li.parentNode);
            ul.select('li', 'ol').each(function(el){
                var contents = $(el.id+'_contents');
                if (el==li) {
                    el.addClassName('is-current');
                    contents.addClassName('is-visible');
                } else {
                    el.removeClassName('is-current');
                    contents.removeClassName('is-visible');
                }
            });
        }
    }
    new Varien.Tabs('.tabs__labels');
    var width = 100 / $$('.product__tabs .tabs__labels-wrapper .tabs__labels li').length;
    $$('.product__tabs .tabs__labels-wrapper .tabs__labels li').each(function(e) {
        e.setStyle({'width':width + '%'});
    }.bind(width));

    if(navigator.userAgent.match(/Android/i)) {
        var docElem = $$('.page-scroll-wrapper')[0];
        var socTop = $$('.tabs__labels-wrapper')[0].offsetTop;
        Event.observe(docElem, 'scroll', function(){
            if(socTop < docElem.scrollTop + document.body.scrollTop){
                $$('.tabs__labels-wrapper')[0].addClassName('fixed-product-tabs');
                if (window.topFlag) {
                    $$('.tabs__labels-wrapper')[0].setStyle({top:'84px'});
                } else {
                    $$('.tabs__labels-wrapper')[0].setStyle({top:'0'});
                }
            }else{
                $$('.tabs__labels-wrapper')[0].removeClassName('fixed-product-tabs');
            }
        });
    }
    //]]>
</script>