<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Mobile2
 * @version    2.0.2
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><div class="dashboard-section island">
    <p class="dashboard__edit"><a href="<?php echo $this->getAddressBookUrl() ?>" class="dashboard__edit-button"><?php echo $this->__('Manage Addresses') ?></a></p>
    <h2 class="dashboard-section__title"><?php echo $this->__('Address Book') ?></h2>
    <div class="dashboard-section__content">
        <div class="address-book">
            <div class="address-book__section">
                <div class="address-book__address-block">
                    <p class="dashboard__edit"><a href="<?php echo $this->getPrimaryBillingAddressEditUrl() ?>" class="dashboard__edit-button"><?php echo $this->__('Edit Address') ?></a></p>
                    <h3 class="address-book__address-title"><?php echo $this->__('Default Billing Address') ?></h3>
                    <address class="address-book__address">
                        <p>
                            <?php echo $this->getPrimaryBillingAddressHtml() ?>
                        </p>
                    </address>
                </div><!-- .address-book__address-block -->
                <div class="address-book__address-block">
                    <p class="dashboard__edit"><a href="<?php echo $this->getPrimaryShippingAddressEditUrl() ?>" class="dashboard__edit-button"><?php echo $this->__('Edit Address') ?></a></p>

                    <h3 class="address-book__address-title"><?php echo $this->__('Default Shipping Address') ?></h3>
                    <address class="address-book__address">
                        <p>
                            <?php echo $this->getPrimaryShippingAddressHtml() ?>
                        </p>
                    </address>
                </div><!-- .address-book__address-block -->
            </div><!-- .address-book__section -->
        </div>
    </div><!-- .checkout-step__content -->
</div><!-- .island -->