<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Mobile2
 * @version    2.0.2
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><div class="dashboard-section island">
    <p class="dashboard__edit"><a href="<?php echo $this->getUrl('customer/account/edit') ?>" class="dashboard__edit-button"><?php echo $this->__('Edit') ?></a></p>

    <h2 class="dashboard-section__title"><?php echo $this->__('Contact Information') ?></h2>

    <div class="dashboard-section__content">
        <p class="customer-name"><?php echo $this->htmlEscape($this->getCustomer()->getName()) ?></p>
        <p>
            <?php echo $this->htmlEscape($this->getCustomer()->getEmail()) ?><br>
            <a href="<?php echo $this->getChangePasswordUrl() ?>"><?php echo $this->__('Change Password') ?></a>
        </p>
    </div><!-- .checkout-step__content -->
</div><!-- .island -->
<?php if( $this->isNewsletterEnabled() ): ?>
    <div class="dashboard-section island">
        <p class="dashboard__edit"><a href="<?php echo $this->getUrl('newsletter/manage') ?>" class="dashboard__edit-button"><?php echo $this->__('Edit') ?></a></p>
        <h2 class="dashboard-section__title"><?php echo $this->__('Newsletters') ?></h2>
        <div class="dashboard-section__content">
            <?php if( $this->getIsSubscribed() ): ?>
                <?php echo $this->__("You are currently subscribed to 'General Subscription'.") ?>
            <?php else: ?>
                <?php echo $this->__('You are currently not subscribed to any newsletter.') ?>
            <?php endif; ?>
        </div><!-- .checkout-step__content -->
    </div><!-- .island -->
<?php endif; ?>