<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Mobile2
 * @version    2.0.2
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><?php /* @var $this Mage_Core_Block_Captcha_Zend */ ?>

<?php /* @var $captcha Mage_Core_Model_Captcha_Zend */ ?>
<?php $captcha = $this->getCaptchaModel() ?>
<p class="form__field form__field--required" id="captcha-input-box-<?php echo $this->getFormId()?>">
    <label  for="captcha_<?php echo $this->getFormId() ?>" class="form__label form__label--required"><?php echo $this->__('Please type the letters below') ?></label>
    <input type="text" class="form__textfield textfield required-entry" name="<?php echo Mage_Captcha_Helper_Data::INPUT_NAME_FIELD_VALUE ?>[<?php echo $this->getFormId()?>]" id="captcha_<?php echo $this->getFormId() ?>" />
</p><!-- .form__field -->
<div class="form__field">
    <div class="form__field captcha-image" id="captcha-image-box-<?php echo $this->getFormId()?>">
        <img id="captcha-reload-<?php echo $this->getFormId() ?>" class="captcha-reload" src="<?php echo $this->getSkinUrl('images/reload.png') ?>" alt="<?php echo $this->__('Reload captcha') ?>" onclick="$('<?php echo $this->getFormId() ?>').captcha.refresh(this)">
        <img id="<?php echo $this->getFormId() ?>" class="captcha-img" height="<?php echo $this->getImgHeight() ?>" src="<?php echo $captcha->getImgSrc() ?>"/>
        <?php if ($captcha->isCaseSensitive()) :?>
            <div class="captcha-note">
                <?php echo $this->__('<strong>Attention</strong>: Captcha is case sensitive.') ?>
            </div>
        <?php endif; ?>
    </div>
    <script type="text/javascript">
    //<![CDATA[
        $('<?php echo $this->getFormId() ?>').captcha = new Captcha('<?php echo $this->getRefreshUrl() ?>', '<?php echo $this->getFormId() ?>');
    //]]>
    </script>
</div>

