<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Mobile2
 * @version    2.0.2
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><div class="add-to-cart-options panel panel--from-right">
    <div class="panel__container">
        <div class="product-options add-to-cart-options__container-inner" id="product-options-wrapper">
            <?php echo $this->getChildHtml('', true, true);?>
            <p class="add-to-cart-options__submit-wrapper">
                <button type="button" onclick="window.productAddToCartFormPopup.submit()" class="green-button" style="background-color:#F4A137;"><?php echo $this->__('Add to Cart');?></button>
            </p>
        </div>
    </div>
</div>
<script type="text/javascript">
    //<![CDATA[
    window.productAddToCartFormPopup = new awMobile2.app.ajaxAddProductToCart('product_addtocart_form');
    window.productAddToCartFormPopup.submit = function(){
        if (this.sendRequest()) {
            window.optionPopup.close();
        }
    }.bind(window.productAddToCartFormPopup);
    $('product-options-wrapper').select('span.label').each(function(span){
        var html = span.innerHTML;
        var parent = span.up();
        parent.innerHTML = parent.innerHTML + html;
        parent.select('script').each(function(script){
            script.remove();
        });
    });
    $$('#product-options-wrapper span.label').each(function(el){el.remove()});
    //]]>
</script>