<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <?php echo $this->getChildHtml('head') ?>
</head>
<body>
<?php echo $this->getChildHtml('after_body_start') ?>
<div class="container">
    <div class="container-pusher">
        <?php //echo $this->getChildHtml('topMenu') ?>
        <?php //echo $this->getChildHtml('topSearch');?>
        <div class="wrapper">
            <div id="content_top">
                <?php echo $this->getChildHtml('header') ?>
                <?php $breadcrumbs = $this->getChildHtml('breadcrumbs');?>
                <?php echo $breadcrumbs;?>
            </div>
			
            <div id="main" class="page">
                <div class="page-scroll-wrapper">
                    <div class="page-scroll">
                        <div id="page_content" class="page-content <?php if(trim($breadcrumbs) == '') echo 'no-padding'?>">
                            <div class="global-messages">
                                <?php echo $this->getChildHtml('global_messages') ?>
                            </div>
                            <?php echo $this->getChildHtml('content') ?>
                        </div>
                        <footer class="footer"><?php echo $this->getChildHtml('footer') ?></footer><!-- .footer -->
                    </div>
                </div>
                <?php echo $this->getChildHtml('before_body_end') ?>
            </div>
        </div><!-- .wrapper -->
        <?php echo $this->getChildHtml('customer_account') ?>
    </div><!-- .container-pusher -->
    <?php echo $this->getChildHtml('loaders') ?>
    <script type="text/javascript">
        //<![CDATA[
            FastClick.attach(document.body);
        //]]>
    </script>
</div><!-- .container -->
</body>
</html>
