<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Mobile2
 * @version    2.0.2
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><div class="cart-top-container panel__container" style="top:0;">
    <div class="page-scroll-wrapper">
        <div class="page-scroll">
            <div class="shopping-cart">
                <div class="shopping-cart__items">
                    <?php echo $this->getMessagesBlock()->addMessages(Mage::getSingleton('checkout/session')->getMessages(true))->getGroupedHtml() ?>
                    <?php echo $this->getChildHtml('form_before') ?>
                    <form id="update_cart_form" class="form" action="<?php echo $this->helper('aw_mobile2/url')->getCartUpdateUrl() ?>" method="post">
                    <?php echo $this->getBlockHtml('formkey'); ?>
                    <?php foreach($this->getItems() as $_item): ?>
                        <?php echo $this->getItemHtml($_item) ?>
                    <?php endforeach ?>
                    </form>
                </div>
                <div class="shopping-cart-bottom">
                    <p class="form__submit-wrapper">
                        <button id="discount_container_link" style="border:1px solid #F4A137; color:#F4A137" class="form__submit button shopping-cart__apply-discount js-open-panel" title="<?php echo $this->__("Discounts")?>" type="button">
                            <span><?php echo $this->__("Apply Discount")?></span>
                        </button>
                    </p>
                    <div class="checkout-methods">
                        <?php echo $this->__('Summary')?>
                        <?php //echo $this->getChildHtml('methods');
                        ?>
                    </div>
                    <?php echo $this->getChildHtml('totals'); ?>
                </div>
                <?php if(!$this->hasError()): ?>
                    <?php echo $this->getChildHtml('checkout.cart.methods.onepage'); ?>
                <?php endif; ?>
            </div>
        </div>
    </div>
</div>
<div class="panel panel--from-bottom">
    <div class="panel__container">
        <div id="discount_container">
            <div class="discount-container-content">
                <?php echo $this->getChildHtml('coupon') ?>
                <?php echo $this->getChildHtml('giftcards') ?>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
/*购物车加减数量*/
jQuery(function(){
	jQuery(".add-to-cart__l").click(function(){
			var quantity = jQuery(this).siblings(".add-to-cart__quantity");
			if(quantity.val()>1){
					quantity.val(parseInt(quantity.val())-1);
				}
			else{
					jQuery(".add-to-cart__l").css("background-color","#ccc");
				}
		});
	jQuery(".add-to-cart__r").click(function(){
			var quantity = jQuery(this).siblings(".add-to-cart__quantity");
			quantity.val(parseInt(quantity.val())+1);
		});
})
//<![CDATA[
window.updateCart = new awMobile2.app.AjaxUpdater('update_cart_form', null);
var discountPopup = new awMobile2.app.popup();
Quo($('discount_container_link')).tap(function(e){
    discountPopup.open($('discount_container'), <?php echo Zend_Json::encode($this->__('Discounts'));?>, '', function() {}, false);
}.bind(discountPopup));
Event.observe(window, 'load', function(e){
    if (window.location.href.search('#cart') != -1 && $('aw-giftcard-info-block')) {
        discountPopup.open($('discount_container'), <?php echo Zend_Json::encode($this->__('Discounts'));?>, '', function() {}, false);
    }
});
//]]>
</script>
