<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Mobile2
 * @version    2.0.2
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><div class="checkout-success">
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <h2 class="checkout-success__title"><?php echo $this->__('Thank you for your purchase!')?></h2>
    <?php if ($this->getOrderId()):?>
        <?php if ($this->getCanViewOrder()) :?>
            <p><?php echo $this->__('Your order # is: %s.', sprintf('<a href="%s">%s</a>', $this->escapeHtml($this->getViewOrderUrl()), $this->escapeHtml($this->getOrderId()))) ?></p>
        <?php  else :?>
            <p><?php echo $this->__('Your order # is: %s.', $this->escapeHtml($this->getOrderId())) ?>.</p>
        <?php endif;?>
        <p><?php echo $this->__('You will receive an order confirmation email with details of your order and a link to track its progress.') ?></p>
        <?php if ($this->getCanViewOrder() && $this->getCanPrintOrder()) :?>
            <p>
                <?php echo $this->getChildHtml() ?>
            </p>
        <?php endif;?>
    <?php endif;?>
    <?php if ($this->getAgreementRefId()): ?>
        <p><?php echo $this->__('Your billing agreement # is: %s.', sprintf('<a href="%s">%s</a>', $this->escapeHtml($this->getAgreementUrl()), $this->escapeHtml($this->getAgreementRefId())))?></p>
    <?php endif;?>
    <?php if ($profiles = $this->getRecurringProfiles()):?>
        <p><?php echo $this->__('Your recurring payment profiles:'); ?></p>
        <ul>
            <?php foreach($profiles as $profile):?>
                <?php $profileIdHtml = ($this->getCanViewProfiles() ? sprintf('<a href="%s">%s</a>', $this->escapeHtml($this->getProfileUrl($profile)), $this->escapeHtml($this->getObjectData($profile, 'reference_id'))) : $this->escapeHtml($this->getObjectData($profile, 'reference_id')));?>
                <li><?php echo $this->__('Payment profile # %s: "%s".', $profileIdHtml, $this->escapeHtml($this->getObjectData($profile, 'schedule_description')))?></li>
            <?php endforeach;?>
        </ul>
    <?php endif;?>
    <p><a href="javascript:window.location='<?php echo $this->getUrl() ?>'" class="button"><?php echo $this->__('Continue Shopping') ?></a></p>
</div>