<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Mobile2
 * @version    2.0.2
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><?php if ($this->getTotal()->getValue()): ?>
    <tr class="shopping-cart-summary__row">
        <td colspan="<?php echo $this->getColspan(); ?>" class="shopping-cart-summary__name">
            <?php $_title = $this->__('Remove'); ?>
            <?php $_url = Mage::getUrl('enterprise_customerbalance/cart/remove'); ?>
            <a href="<?php echo $_url; ?>" title="<?php echo $_title; ?>" class="btn-remove"><img src="<?php echo $this->getSkinUrl('images/btn_remove.gif') ?>" alt="<?php echo $this->__('Remove')?>" /></a>
            <?php echo $this->getTotal()->getTitle(); ?>
        </td>
        <td class="shopping-cart-summary__price">
            <?php echo $this->helper('checkout')->formatPrice($this->getTotal()->getValue()) ?>
        </td>
    </tr>
<?php endif; ?>
