<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Mobile2
 * @version    2.0.2
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><?php if ($_products = $this->getRecentlyViewedProducts()): ?>
    <div class="related-products">
        <h3 class="related-products__title"><?php echo $this->__('Recently Viewed') ?></h3>
        <div class="related-products__list">
            <?php foreach($_products as $_item): ?>
                <div class="product-card" onclick="setLocation('<?php echo $_item->getProductUrl() ?>')">
                    <p class="product-card__image-wrapper">
                        <img src="<?php echo $this->helper('catalog/image')->init($_item, 'small_image')->resize(118); ?>" alt="<?php echo $this->htmlEscape($_item->getName()) ?>" class="product-card__image">
                    </p>
                    <div class="product-card__info">
                        <h3 class="product-card__title">
                <span class="product-card__title-inner">
                    <?php echo $this->htmlEscape($_item->getName()) ?>
                </span>
                        </h3>
                        <?php echo $this->getReviewsSummaryHtml($_item, 'short', false)?>
                        <?php echo $this->getPriceHtml($_item, true, '-related');?>
                    </div><!-- .product-card__info -->
                </div>
            <?php endforeach ?>
        </div>
    </div>
<?php endif; ?>